projects:
    students:
        schemaPath: packages/graphql/src/schema.json
        includes:
            - packages/graphql/src/**/*.ts
        excludes:
            - ./amplify/**
        extensions:
            amplify:
                codeGenTarget: typescript
                generatedFileName: packages/graphql/src/API.ts
                docsFilePath: packages/graphql/src
                maxDepth: 3
extensions:
    amplify:
        version: 3
