/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:3928d3f5-abb9-4cd7-96d5-bbf1e11e601b",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_toIr1ygEg",
    "aws_user_pools_web_client_id": "233j2993ca074vpr1cod7d0jii",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fbtuf6bm4bcrllp2ix5sdfmyjq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-mgsxxjw53jfyzjhhactyn3fomi",
    "aws_cloud_logic_custom": [
        {
            "name": "REST",
            "endpoint": "https://2cg2y5lqq9.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_user_files_s3_bucket": "applyfuture-students-content162403-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
