"use strict";
/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.
Object.defineProperty(exports, "__esModule", { value: true });
exports.SearchablePostSortableFields = exports.SearchableProgramSortableFields = exports.SearchableSchoolSortableFields = exports.SearchableFeedbackSortableFields = exports.SearchableSearchAlertSortableFields = exports.SearchableApplicationSortableFields = exports.SearchableSortDirection = exports.SearchableStudentSortableFields = exports.ModelSortDirection = exports.ModelAttributeTypes = void 0;
var ModelAttributeTypes;
(function (ModelAttributeTypes) {
    ModelAttributeTypes["binary"] = "binary";
    ModelAttributeTypes["binarySet"] = "binarySet";
    ModelAttributeTypes["bool"] = "bool";
    ModelAttributeTypes["list"] = "list";
    ModelAttributeTypes["map"] = "map";
    ModelAttributeTypes["number"] = "number";
    ModelAttributeTypes["numberSet"] = "numberSet";
    ModelAttributeTypes["string"] = "string";
    ModelAttributeTypes["stringSet"] = "stringSet";
    ModelAttributeTypes["_null"] = "_null";
})(ModelAttributeTypes = exports.ModelAttributeTypes || (exports.ModelAttributeTypes = {}));
var ModelSortDirection;
(function (ModelSortDirection) {
    ModelSortDirection["ASC"] = "ASC";
    ModelSortDirection["DESC"] = "DESC";
})(ModelSortDirection = exports.ModelSortDirection || (exports.ModelSortDirection = {}));
var SearchableStudentSortableFields;
(function (SearchableStudentSortableFields) {
    SearchableStudentSortableFields["id"] = "id";
    SearchableStudentSortableFields["address"] = "address";
    SearchableStudentSortableFields["birthday"] = "birthday";
    SearchableStudentSortableFields["city"] = "city";
    SearchableStudentSortableFields["country"] = "country";
    SearchableStudentSortableFields["degrees"] = "degrees";
    SearchableStudentSortableFields["disciplines"] = "disciplines";
    SearchableStudentSortableFields["educationCountry"] = "educationCountry";
    SearchableStudentSortableFields["email"] = "email";
    SearchableStudentSortableFields["fatherFirstName"] = "fatherFirstName";
    SearchableStudentSortableFields["fatherLastName"] = "fatherLastName";
    SearchableStudentSortableFields["firstLanguage"] = "firstLanguage";
    SearchableStudentSortableFields["firstName"] = "firstName";
    SearchableStudentSortableFields["favoritePrograms"] = "favoritePrograms";
    SearchableStudentSortableFields["favoriteSchools"] = "favoriteSchools";
    SearchableStudentSortableFields["gender"] = "gender";
    SearchableStudentSortableFields["gradePointAverage"] = "gradePointAverage";
    SearchableStudentSortableFields["guardianFirstName"] = "guardianFirstName";
    SearchableStudentSortableFields["guardianLastName"] = "guardianLastName";
    SearchableStudentSortableFields["hasMandatoryDocuments"] = "hasMandatoryDocuments";
    SearchableStudentSortableFields["highestEducationLevel"] = "highestEducationLevel";
    SearchableStudentSortableFields["lastName"] = "lastName";
    SearchableStudentSortableFields["lastUpdate"] = "lastUpdate";
    SearchableStudentSortableFields["locale"] = "locale";
    SearchableStudentSortableFields["maritalStatus"] = "maritalStatus";
    SearchableStudentSortableFields["middleName"] = "middleName";
    SearchableStudentSortableFields["modalProfileCompletedViewed"] = "modalProfileCompletedViewed";
    SearchableStudentSortableFields["phoneNumber"] = "phoneNumber";
    SearchableStudentSortableFields["motherFirstName"] = "motherFirstName";
    SearchableStudentSortableFields["motherMaidenName"] = "motherMaidenName";
    SearchableStudentSortableFields["nationality"] = "nationality";
    SearchableStudentSortableFields["parentsAddress"] = "parentsAddress";
    SearchableStudentSortableFields["parentsCity"] = "parentsCity";
    SearchableStudentSortableFields["parentsCountry"] = "parentsCountry";
    SearchableStudentSortableFields["parentsEmail"] = "parentsEmail";
    SearchableStudentSortableFields["parentsPhoneNumber"] = "parentsPhoneNumber";
    SearchableStudentSortableFields["passportNumber"] = "passportNumber";
    SearchableStudentSortableFields["refusedVisa"] = "refusedVisa";
    SearchableStudentSortableFields["refusedVisaReason"] = "refusedVisaReason";
    SearchableStudentSortableFields["testCambridgeAdvanced"] = "testCambridgeAdvanced";
    SearchableStudentSortableFields["testCambridgeAdvancedDate"] = "testCambridgeAdvancedDate";
    SearchableStudentSortableFields["testCambridgeFirst"] = "testCambridgeFirst";
    SearchableStudentSortableFields["testCambridgeFirstDate"] = "testCambridgeFirstDate";
    SearchableStudentSortableFields["testCeliCilsItPlida"] = "testCeliCilsItPlida";
    SearchableStudentSortableFields["testCeliCilsItPlidaDate"] = "testCeliCilsItPlidaDate";
    SearchableStudentSortableFields["testDele"] = "testDele";
    SearchableStudentSortableFields["testDeleDate"] = "testDeleDate";
    SearchableStudentSortableFields["testDelfdalf"] = "testDelfdalf";
    SearchableStudentSortableFields["testDelfdalfDate"] = "testDelfdalfDate";
    SearchableStudentSortableFields["testEnglishPending"] = "testEnglishPending";
    SearchableStudentSortableFields["testGmat"] = "testGmat";
    SearchableStudentSortableFields["testGmatDate"] = "testGmatDate";
    SearchableStudentSortableFields["testGoethe"] = "testGoethe";
    SearchableStudentSortableFields["testGoetheDate"] = "testGoetheDate";
    SearchableStudentSortableFields["testGre"] = "testGre";
    SearchableStudentSortableFields["testGreDate"] = "testGreDate";
    SearchableStudentSortableFields["testIelts"] = "testIelts";
    SearchableStudentSortableFields["testIeltsDate"] = "testIeltsDate";
    SearchableStudentSortableFields["testLogicAndReasoningPending"] = "testLogicAndReasoningPending";
    SearchableStudentSortableFields["testOtherLanguagesPending"] = "testOtherLanguagesPending";
    SearchableStudentSortableFields["testTagemage"] = "testTagemage";
    SearchableStudentSortableFields["testTagemageDate"] = "testTagemageDate";
    SearchableStudentSortableFields["testTcftef"] = "testTcftef";
    SearchableStudentSortableFields["testTcftefDate"] = "testTcftefDate";
    SearchableStudentSortableFields["testToefl"] = "testToefl";
    SearchableStudentSortableFields["testToeflDate"] = "testToeflDate";
    SearchableStudentSortableFields["testToeic"] = "testToeic";
    SearchableStudentSortableFields["testToeicDate"] = "testToeicDate";
    SearchableStudentSortableFields["validVisa"] = "validVisa";
})(SearchableStudentSortableFields = exports.SearchableStudentSortableFields || (exports.SearchableStudentSortableFields = {}));
var SearchableSortDirection;
(function (SearchableSortDirection) {
    SearchableSortDirection["asc"] = "asc";
    SearchableSortDirection["desc"] = "desc";
})(SearchableSortDirection = exports.SearchableSortDirection || (exports.SearchableSortDirection = {}));
var SearchableApplicationSortableFields;
(function (SearchableApplicationSortableFields) {
    SearchableApplicationSortableFields["id"] = "id";
    SearchableApplicationSortableFields["admissionResult"] = "admissionResult";
    SearchableApplicationSortableFields["document"] = "document";
    SearchableApplicationSortableFields["decisionLetterDate"] = "decisionLetterDate";
    SearchableApplicationSortableFields["intake"] = "intake";
    SearchableApplicationSortableFields["interviewDate"] = "interviewDate";
    SearchableApplicationSortableFields["lastUpdate"] = "lastUpdate";
    SearchableApplicationSortableFields["modalApplicationCompletedViewed"] = "modalApplicationCompletedViewed";
    SearchableApplicationSortableFields["programId"] = "programId";
    SearchableApplicationSortableFields["studentId"] = "studentId";
    SearchableApplicationSortableFields["todo"] = "todo";
    SearchableApplicationSortableFields["tuitionsFeePaymentDate"] = "tuitionsFeePaymentDate";
    SearchableApplicationSortableFields["visaDate"] = "visaDate";
})(SearchableApplicationSortableFields = exports.SearchableApplicationSortableFields || (exports.SearchableApplicationSortableFields = {}));
var SearchableSearchAlertSortableFields;
(function (SearchableSearchAlertSortableFields) {
    SearchableSearchAlertSortableFields["id"] = "id";
    SearchableSearchAlertSortableFields["lastUpdate"] = "lastUpdate";
    SearchableSearchAlertSortableFields["studentId"] = "studentId";
    SearchableSearchAlertSortableFields["type"] = "type";
    SearchableSearchAlertSortableFields["query"] = "query";
})(SearchableSearchAlertSortableFields = exports.SearchableSearchAlertSortableFields || (exports.SearchableSearchAlertSortableFields = {}));
var SearchableFeedbackSortableFields;
(function (SearchableFeedbackSortableFields) {
    SearchableFeedbackSortableFields["id"] = "id";
    SearchableFeedbackSortableFields["applicationId"] = "applicationId";
    SearchableFeedbackSortableFields["lastUpdate"] = "lastUpdate";
    SearchableFeedbackSortableFields["rating"] = "rating";
})(SearchableFeedbackSortableFields = exports.SearchableFeedbackSortableFields || (exports.SearchableFeedbackSortableFields = {}));
var SearchableSchoolSortableFields;
(function (SearchableSchoolSortableFields) {
    SearchableSchoolSortableFields["id"] = "id";
    SearchableSchoolSortableFields["city"] = "city";
    SearchableSchoolSortableFields["country"] = "country";
    SearchableSchoolSortableFields["coverPhoto"] = "coverPhoto";
    SearchableSchoolSortableFields["contactEmail"] = "contactEmail";
    SearchableSchoolSortableFields["contactJobTitle"] = "contactJobTitle";
    SearchableSchoolSortableFields["contactName"] = "contactName";
    SearchableSchoolSortableFields["contactPhone"] = "contactPhone";
    SearchableSchoolSortableFields["contractStatus"] = "contractStatus";
    SearchableSchoolSortableFields["creationYear"] = "creationYear";
    SearchableSchoolSortableFields["description"] = "description";
    SearchableSchoolSortableFields["institutionType"] = "institutionType";
    SearchableSchoolSortableFields["internationalStudents"] = "internationalStudents";
    SearchableSchoolSortableFields["lastUpdate"] = "lastUpdate";
    SearchableSchoolSortableFields["logo"] = "logo";
    SearchableSchoolSortableFields["name"] = "name";
    SearchableSchoolSortableFields["totalStudents"] = "totalStudents";
    SearchableSchoolSortableFields["slug"] = "slug";
    SearchableSchoolSortableFields["published"] = "published";
})(SearchableSchoolSortableFields = exports.SearchableSchoolSortableFields || (exports.SearchableSchoolSortableFields = {}));
var SearchableProgramSortableFields;
(function (SearchableProgramSortableFields) {
    SearchableProgramSortableFields["id"] = "id";
    SearchableProgramSortableFields["applicationFee"] = "applicationFee";
    SearchableProgramSortableFields["applicationFeeCurrency"] = "applicationFeeCurrency";
    SearchableProgramSortableFields["city"] = "city";
    SearchableProgramSortableFields["costOfLiving"] = "costOfLiving";
    SearchableProgramSortableFields["costOfLivingCurrency"] = "costOfLivingCurrency";
    SearchableProgramSortableFields["country"] = "country";
    SearchableProgramSortableFields["degree"] = "degree";
    SearchableProgramSortableFields["description"] = "description";
    SearchableProgramSortableFields["discipline"] = "discipline";
    SearchableProgramSortableFields["duration"] = "duration";
    SearchableProgramSortableFields["durationUnit"] = "durationUnit";
    SearchableProgramSortableFields["fee"] = "fee";
    SearchableProgramSortableFields["feeCurrency"] = "feeCurrency";
    SearchableProgramSortableFields["feeUnit"] = "feeUnit";
    SearchableProgramSortableFields["feesAndFinancing"] = "feesAndFinancing";
    SearchableProgramSortableFields["gradePointAverage"] = "gradePointAverage";
    SearchableProgramSortableFields["highestEducationLevel"] = "highestEducationLevel";
    SearchableProgramSortableFields["intakeInformation"] = "intakeInformation";
    SearchableProgramSortableFields["intakes"] = "intakes";
    SearchableProgramSortableFields["languages"] = "languages";
    SearchableProgramSortableFields["lastUpdate"] = "lastUpdate";
    SearchableProgramSortableFields["minimumAge"] = "minimumAge";
    SearchableProgramSortableFields["minimumWorkExperience"] = "minimumWorkExperience";
    SearchableProgramSortableFields["minimumWorkExperienceUnit"] = "minimumWorkExperienceUnit";
    SearchableProgramSortableFields["name"] = "name";
    SearchableProgramSortableFields["otherRequirements"] = "otherRequirements";
    SearchableProgramSortableFields["published"] = "published";
    SearchableProgramSortableFields["schedule"] = "schedule";
    SearchableProgramSortableFields["schoolId"] = "schoolId";
    SearchableProgramSortableFields["schoolName"] = "schoolName";
    SearchableProgramSortableFields["slug"] = "slug";
    SearchableProgramSortableFields["submissionDeadline"] = "submissionDeadline";
    SearchableProgramSortableFields["testCambridgeAdvanced"] = "testCambridgeAdvanced";
    SearchableProgramSortableFields["testCambridgeFirst"] = "testCambridgeFirst";
    SearchableProgramSortableFields["testCeliCilsItPlida"] = "testCeliCilsItPlida";
    SearchableProgramSortableFields["testDele"] = "testDele";
    SearchableProgramSortableFields["testDelfdalf"] = "testDelfdalf";
    SearchableProgramSortableFields["testGmat"] = "testGmat";
    SearchableProgramSortableFields["testGoethe"] = "testGoethe";
    SearchableProgramSortableFields["testGre"] = "testGre";
    SearchableProgramSortableFields["testIelts"] = "testIelts";
    SearchableProgramSortableFields["testTagemage"] = "testTagemage";
    SearchableProgramSortableFields["testTcftef"] = "testTcftef";
    SearchableProgramSortableFields["testToefl"] = "testToefl";
    SearchableProgramSortableFields["testToeic"] = "testToeic";
})(SearchableProgramSortableFields = exports.SearchableProgramSortableFields || (exports.SearchableProgramSortableFields = {}));
var SearchablePostSortableFields;
(function (SearchablePostSortableFields) {
    SearchablePostSortableFields["id"] = "id";
    SearchablePostSortableFields["category"] = "category";
    SearchablePostSortableFields["content"] = "content";
    SearchablePostSortableFields["lastUpdate"] = "lastUpdate";
    SearchablePostSortableFields["published"] = "published";
    SearchablePostSortableFields["slug"] = "slug";
    SearchablePostSortableFields["title"] = "title";
})(SearchablePostSortableFields = exports.SearchablePostSortableFields || (exports.SearchablePostSortableFields = {}));
//# sourceMappingURL=API.js.map