/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onUpdateApplicationById = /* GraphQL */ `
  subscription OnUpdateApplicationById($id: ID!) {
    onUpdateApplicationById(id: $id) {
      id
      admissionResult
      document
      decisionLetterDate
      intake
      interviewDate
      lastUpdate
      modalApplicationCompletedViewed
      notifications {
        date
        description
        descriptionOptions
        link
        seen
        title
        titleOptions
      }
      programId
      steps {
        date
        id
        isMandatory
        label
        status
        timelineLabel
      }
      studentId
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      todo
      tuitionsFeePaymentDate
      visaDate
      createdAt
      updatedAt
      owner
      program {
        id
        applicationFee
        applicationFeeCurrency
        city
        costOfLiving
        costOfLivingCurrency
        country
        degree
        description
        discipline
        duration
        durationUnit
        fee
        feeCurrency
        feeUnit
        feesAndFinancing
        gradePointAverage
        highestEducationLevel
        intakeInformation
        intakes
        languages
        lastUpdate
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        name
        otherRequirements
        published
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        schedule
        schoolId
        schoolName
        slug
        submissionDeadline
        testCambridgeAdvanced
        testCambridgeFirst
        testCeliCilsItPlida
        testDele
        testDelfdalf
        testGmat
        testGoethe
        testGre
        testIelts
        testTagemage
        testTcftef
        testToefl
        testToeic
        createdAt
        updatedAt
        owner
        school {
          id
          city
          country
          coverPhoto
          contactEmail
          contactJobTitle
          contactName
          contactPhone
          contractStatus
          creationYear
          description
          institutionType
          internationalStudents
          lastUpdate
          logo
          name
          totalStudents
          slug
          published
          createdAt
          updatedAt
          owner
        }
      }
    }
  }
`;
export const onCreateStudent = /* GraphQL */ `
  subscription OnCreateStudent($owner: String) {
    onCreateStudent(owner: $owner) {
      id
      address
      applications {
        items {
          id
          admissionResult
          document
          decisionLetterDate
          intake
          interviewDate
          lastUpdate
          modalApplicationCompletedViewed
          programId
          studentId
          todo
          tuitionsFeePaymentDate
          visaDate
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      birthday
      city
      country
      degrees
      disciplines
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      educationCountry
      email
      fatherFirstName
      fatherLastName
      firstLanguage
      firstName
      favoritePrograms
      favoriteSchools
      gender
      gradePointAverage
      guardianFirstName
      guardianLastName
      hasMandatoryDocuments
      highestEducationLevel
      lastName
      lastUpdate
      locale
      maritalStatus
      middleName
      modalProfileCompletedViewed
      phoneNumber
      motherFirstName
      motherMaidenName
      nationality
      notifications {
        date
        description
        descriptionOptions
        link
        seen
        title
        titleOptions
      }
      parentsAddress
      parentsCity
      parentsCountry
      parentsEmail
      parentsPhoneNumber
      passportNumber
      refusedVisa
      refusedVisaReason
      schoolsAttended {
        address
        attendedInstitutionFrom
        attendedInstitutionTo
        city
        country
        degreeAwarded
        degreeAwardedOn
        educationLevel
        name
        primaryLanguageInstruction
      }
      testCambridgeAdvanced
      testCambridgeAdvancedDate
      testCambridgeFirst
      testCambridgeFirstDate
      testCeliCilsItPlida
      testCeliCilsItPlidaDate
      testDele
      testDeleDate
      testDelfdalf
      testDelfdalfDate
      testEnglishPending
      testGmat
      testGmatDate
      testGoethe
      testGoetheDate
      testGre
      testGreDate
      testIelts
      testIeltsDate
      testLogicAndReasoningPending
      testOtherLanguagesPending
      testTagemage
      testTagemageDate
      testTcftef
      testTcftefDate
      testToefl
      testToeflDate
      testToeic
      testToeicDate
      validVisa
      workExperiences {
        address
        compagnyName
        title
        workedFrom
        workedTo
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateStudent = /* GraphQL */ `
  subscription OnUpdateStudent($owner: String) {
    onUpdateStudent(owner: $owner) {
      id
      address
      applications {
        items {
          id
          admissionResult
          document
          decisionLetterDate
          intake
          interviewDate
          lastUpdate
          modalApplicationCompletedViewed
          programId
          studentId
          todo
          tuitionsFeePaymentDate
          visaDate
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      birthday
      city
      country
      degrees
      disciplines
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      educationCountry
      email
      fatherFirstName
      fatherLastName
      firstLanguage
      firstName
      favoritePrograms
      favoriteSchools
      gender
      gradePointAverage
      guardianFirstName
      guardianLastName
      hasMandatoryDocuments
      highestEducationLevel
      lastName
      lastUpdate
      locale
      maritalStatus
      middleName
      modalProfileCompletedViewed
      phoneNumber
      motherFirstName
      motherMaidenName
      nationality
      notifications {
        date
        description
        descriptionOptions
        link
        seen
        title
        titleOptions
      }
      parentsAddress
      parentsCity
      parentsCountry
      parentsEmail
      parentsPhoneNumber
      passportNumber
      refusedVisa
      refusedVisaReason
      schoolsAttended {
        address
        attendedInstitutionFrom
        attendedInstitutionTo
        city
        country
        degreeAwarded
        degreeAwardedOn
        educationLevel
        name
        primaryLanguageInstruction
      }
      testCambridgeAdvanced
      testCambridgeAdvancedDate
      testCambridgeFirst
      testCambridgeFirstDate
      testCeliCilsItPlida
      testCeliCilsItPlidaDate
      testDele
      testDeleDate
      testDelfdalf
      testDelfdalfDate
      testEnglishPending
      testGmat
      testGmatDate
      testGoethe
      testGoetheDate
      testGre
      testGreDate
      testIelts
      testIeltsDate
      testLogicAndReasoningPending
      testOtherLanguagesPending
      testTagemage
      testTagemageDate
      testTcftef
      testTcftefDate
      testToefl
      testToeflDate
      testToeic
      testToeicDate
      validVisa
      workExperiences {
        address
        compagnyName
        title
        workedFrom
        workedTo
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteStudent = /* GraphQL */ `
  subscription OnDeleteStudent($owner: String) {
    onDeleteStudent(owner: $owner) {
      id
      address
      applications {
        items {
          id
          admissionResult
          document
          decisionLetterDate
          intake
          interviewDate
          lastUpdate
          modalApplicationCompletedViewed
          programId
          studentId
          todo
          tuitionsFeePaymentDate
          visaDate
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      birthday
      city
      country
      degrees
      disciplines
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      educationCountry
      email
      fatherFirstName
      fatherLastName
      firstLanguage
      firstName
      favoritePrograms
      favoriteSchools
      gender
      gradePointAverage
      guardianFirstName
      guardianLastName
      hasMandatoryDocuments
      highestEducationLevel
      lastName
      lastUpdate
      locale
      maritalStatus
      middleName
      modalProfileCompletedViewed
      phoneNumber
      motherFirstName
      motherMaidenName
      nationality
      notifications {
        date
        description
        descriptionOptions
        link
        seen
        title
        titleOptions
      }
      parentsAddress
      parentsCity
      parentsCountry
      parentsEmail
      parentsPhoneNumber
      passportNumber
      refusedVisa
      refusedVisaReason
      schoolsAttended {
        address
        attendedInstitutionFrom
        attendedInstitutionTo
        city
        country
        degreeAwarded
        degreeAwardedOn
        educationLevel
        name
        primaryLanguageInstruction
      }
      testCambridgeAdvanced
      testCambridgeAdvancedDate
      testCambridgeFirst
      testCambridgeFirstDate
      testCeliCilsItPlida
      testCeliCilsItPlidaDate
      testDele
      testDeleDate
      testDelfdalf
      testDelfdalfDate
      testEnglishPending
      testGmat
      testGmatDate
      testGoethe
      testGoetheDate
      testGre
      testGreDate
      testIelts
      testIeltsDate
      testLogicAndReasoningPending
      testOtherLanguagesPending
      testTagemage
      testTagemageDate
      testTcftef
      testTcftefDate
      testToefl
      testToeflDate
      testToeic
      testToeicDate
      validVisa
      workExperiences {
        address
        compagnyName
        title
        workedFrom
        workedTo
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateDocument = /* GraphQL */ `
  subscription OnCreateDocument($owner: String) {
    onCreateDocument(owner: $owner) {
      id
      studentId
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      name
      storageKey
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateDocument = /* GraphQL */ `
  subscription OnUpdateDocument($owner: String) {
    onUpdateDocument(owner: $owner) {
      id
      studentId
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      name
      storageKey
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteDocument = /* GraphQL */ `
  subscription OnDeleteDocument($owner: String) {
    onDeleteDocument(owner: $owner) {
      id
      studentId
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      name
      storageKey
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateApplication = /* GraphQL */ `
  subscription OnCreateApplication {
    onCreateApplication {
      id
      admissionResult
      document
      decisionLetterDate
      intake
      interviewDate
      lastUpdate
      modalApplicationCompletedViewed
      notifications {
        date
        description
        descriptionOptions
        link
        seen
        title
        titleOptions
      }
      programId
      steps {
        date
        id
        isMandatory
        label
        status
        timelineLabel
      }
      studentId
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      todo
      tuitionsFeePaymentDate
      visaDate
      createdAt
      updatedAt
      owner
      program {
        id
        applicationFee
        applicationFeeCurrency
        city
        costOfLiving
        costOfLivingCurrency
        country
        degree
        description
        discipline
        duration
        durationUnit
        fee
        feeCurrency
        feeUnit
        feesAndFinancing
        gradePointAverage
        highestEducationLevel
        intakeInformation
        intakes
        languages
        lastUpdate
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        name
        otherRequirements
        published
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        schedule
        schoolId
        schoolName
        slug
        submissionDeadline
        testCambridgeAdvanced
        testCambridgeFirst
        testCeliCilsItPlida
        testDele
        testDelfdalf
        testGmat
        testGoethe
        testGre
        testIelts
        testTagemage
        testTcftef
        testToefl
        testToeic
        createdAt
        updatedAt
        owner
        school {
          id
          city
          country
          coverPhoto
          contactEmail
          contactJobTitle
          contactName
          contactPhone
          contractStatus
          creationYear
          description
          institutionType
          internationalStudents
          lastUpdate
          logo
          name
          totalStudents
          slug
          published
          createdAt
          updatedAt
          owner
        }
      }
    }
  }
`;
export const onUpdateApplication = /* GraphQL */ `
  subscription OnUpdateApplication {
    onUpdateApplication {
      id
      admissionResult
      document
      decisionLetterDate
      intake
      interviewDate
      lastUpdate
      modalApplicationCompletedViewed
      notifications {
        date
        description
        descriptionOptions
        link
        seen
        title
        titleOptions
      }
      programId
      steps {
        date
        id
        isMandatory
        label
        status
        timelineLabel
      }
      studentId
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      todo
      tuitionsFeePaymentDate
      visaDate
      createdAt
      updatedAt
      owner
      program {
        id
        applicationFee
        applicationFeeCurrency
        city
        costOfLiving
        costOfLivingCurrency
        country
        degree
        description
        discipline
        duration
        durationUnit
        fee
        feeCurrency
        feeUnit
        feesAndFinancing
        gradePointAverage
        highestEducationLevel
        intakeInformation
        intakes
        languages
        lastUpdate
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        name
        otherRequirements
        published
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        schedule
        schoolId
        schoolName
        slug
        submissionDeadline
        testCambridgeAdvanced
        testCambridgeFirst
        testCeliCilsItPlida
        testDele
        testDelfdalf
        testGmat
        testGoethe
        testGre
        testIelts
        testTagemage
        testTcftef
        testToefl
        testToeic
        createdAt
        updatedAt
        owner
        school {
          id
          city
          country
          coverPhoto
          contactEmail
          contactJobTitle
          contactName
          contactPhone
          contractStatus
          creationYear
          description
          institutionType
          internationalStudents
          lastUpdate
          logo
          name
          totalStudents
          slug
          published
          createdAt
          updatedAt
          owner
        }
      }
    }
  }
`;
export const onDeleteApplication = /* GraphQL */ `
  subscription OnDeleteApplication {
    onDeleteApplication {
      id
      admissionResult
      document
      decisionLetterDate
      intake
      interviewDate
      lastUpdate
      modalApplicationCompletedViewed
      notifications {
        date
        description
        descriptionOptions
        link
        seen
        title
        titleOptions
      }
      programId
      steps {
        date
        id
        isMandatory
        label
        status
        timelineLabel
      }
      studentId
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      todo
      tuitionsFeePaymentDate
      visaDate
      createdAt
      updatedAt
      owner
      program {
        id
        applicationFee
        applicationFeeCurrency
        city
        costOfLiving
        costOfLivingCurrency
        country
        degree
        description
        discipline
        duration
        durationUnit
        fee
        feeCurrency
        feeUnit
        feesAndFinancing
        gradePointAverage
        highestEducationLevel
        intakeInformation
        intakes
        languages
        lastUpdate
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        name
        otherRequirements
        published
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        schedule
        schoolId
        schoolName
        slug
        submissionDeadline
        testCambridgeAdvanced
        testCambridgeFirst
        testCeliCilsItPlida
        testDele
        testDelfdalf
        testGmat
        testGoethe
        testGre
        testIelts
        testTagemage
        testTcftef
        testToefl
        testToeic
        createdAt
        updatedAt
        owner
        school {
          id
          city
          country
          coverPhoto
          contactEmail
          contactJobTitle
          contactName
          contactPhone
          contractStatus
          creationYear
          description
          institutionType
          internationalStudents
          lastUpdate
          logo
          name
          totalStudents
          slug
          published
          createdAt
          updatedAt
          owner
        }
      }
    }
  }
`;
export const onCreateSearchAlert = /* GraphQL */ `
  subscription OnCreateSearchAlert($owner: String) {
    onCreateSearchAlert(owner: $owner) {
      id
      lastUpdate
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      studentId
      type
      query
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateSearchAlert = /* GraphQL */ `
  subscription OnUpdateSearchAlert($owner: String) {
    onUpdateSearchAlert(owner: $owner) {
      id
      lastUpdate
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      studentId
      type
      query
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteSearchAlert = /* GraphQL */ `
  subscription OnDeleteSearchAlert($owner: String) {
    onDeleteSearchAlert(owner: $owner) {
      id
      lastUpdate
      student {
        id
        address
        applications {
          nextToken
        }
        birthday
        city
        country
        degrees
        disciplines
        documents {
          nextToken
        }
        educationCountry
        email
        fatherFirstName
        fatherLastName
        firstLanguage
        firstName
        favoritePrograms
        favoriteSchools
        gender
        gradePointAverage
        guardianFirstName
        guardianLastName
        hasMandatoryDocuments
        highestEducationLevel
        lastName
        lastUpdate
        locale
        maritalStatus
        middleName
        modalProfileCompletedViewed
        phoneNumber
        motherFirstName
        motherMaidenName
        nationality
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        parentsAddress
        parentsCity
        parentsCountry
        parentsEmail
        parentsPhoneNumber
        passportNumber
        refusedVisa
        refusedVisaReason
        schoolsAttended {
          address
          attendedInstitutionFrom
          attendedInstitutionTo
          city
          country
          degreeAwarded
          degreeAwardedOn
          educationLevel
          name
          primaryLanguageInstruction
        }
        testCambridgeAdvanced
        testCambridgeAdvancedDate
        testCambridgeFirst
        testCambridgeFirstDate
        testCeliCilsItPlida
        testCeliCilsItPlidaDate
        testDele
        testDeleDate
        testDelfdalf
        testDelfdalfDate
        testEnglishPending
        testGmat
        testGmatDate
        testGoethe
        testGoetheDate
        testGre
        testGreDate
        testIelts
        testIeltsDate
        testLogicAndReasoningPending
        testOtherLanguagesPending
        testTagemage
        testTagemageDate
        testTcftef
        testTcftefDate
        testToefl
        testToeflDate
        testToeic
        testToeicDate
        validVisa
        workExperiences {
          address
          compagnyName
          title
          workedFrom
          workedTo
        }
        createdAt
        updatedAt
        owner
      }
      studentId
      type
      query
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateFeedback = /* GraphQL */ `
  subscription OnCreateFeedback($owner: String) {
    onCreateFeedback(owner: $owner) {
      id
      application {
        id
        admissionResult
        document
        decisionLetterDate
        intake
        interviewDate
        lastUpdate
        modalApplicationCompletedViewed
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        programId
        steps {
          date
          id
          isMandatory
          label
          status
          timelineLabel
        }
        studentId
        student {
          id
          address
          birthday
          city
          country
          degrees
          disciplines
          educationCountry
          email
          fatherFirstName
          fatherLastName
          firstLanguage
          firstName
          favoritePrograms
          favoriteSchools
          gender
          gradePointAverage
          guardianFirstName
          guardianLastName
          hasMandatoryDocuments
          highestEducationLevel
          lastName
          lastUpdate
          locale
          maritalStatus
          middleName
          modalProfileCompletedViewed
          phoneNumber
          motherFirstName
          motherMaidenName
          nationality
          parentsAddress
          parentsCity
          parentsCountry
          parentsEmail
          parentsPhoneNumber
          passportNumber
          refusedVisa
          refusedVisaReason
          testCambridgeAdvanced
          testCambridgeAdvancedDate
          testCambridgeFirst
          testCambridgeFirstDate
          testCeliCilsItPlida
          testCeliCilsItPlidaDate
          testDele
          testDeleDate
          testDelfdalf
          testDelfdalfDate
          testEnglishPending
          testGmat
          testGmatDate
          testGoethe
          testGoetheDate
          testGre
          testGreDate
          testIelts
          testIeltsDate
          testLogicAndReasoningPending
          testOtherLanguagesPending
          testTagemage
          testTagemageDate
          testTcftef
          testTcftefDate
          testToefl
          testToeflDate
          testToeic
          testToeicDate
          validVisa
          createdAt
          updatedAt
          owner
        }
        todo
        tuitionsFeePaymentDate
        visaDate
        createdAt
        updatedAt
        owner
        program {
          id
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          intakeInformation
          intakes
          languages
          lastUpdate
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
          owner
        }
      }
      applicationId
      lastUpdate
      rating
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateFeedback = /* GraphQL */ `
  subscription OnUpdateFeedback($owner: String) {
    onUpdateFeedback(owner: $owner) {
      id
      application {
        id
        admissionResult
        document
        decisionLetterDate
        intake
        interviewDate
        lastUpdate
        modalApplicationCompletedViewed
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        programId
        steps {
          date
          id
          isMandatory
          label
          status
          timelineLabel
        }
        studentId
        student {
          id
          address
          birthday
          city
          country
          degrees
          disciplines
          educationCountry
          email
          fatherFirstName
          fatherLastName
          firstLanguage
          firstName
          favoritePrograms
          favoriteSchools
          gender
          gradePointAverage
          guardianFirstName
          guardianLastName
          hasMandatoryDocuments
          highestEducationLevel
          lastName
          lastUpdate
          locale
          maritalStatus
          middleName
          modalProfileCompletedViewed
          phoneNumber
          motherFirstName
          motherMaidenName
          nationality
          parentsAddress
          parentsCity
          parentsCountry
          parentsEmail
          parentsPhoneNumber
          passportNumber
          refusedVisa
          refusedVisaReason
          testCambridgeAdvanced
          testCambridgeAdvancedDate
          testCambridgeFirst
          testCambridgeFirstDate
          testCeliCilsItPlida
          testCeliCilsItPlidaDate
          testDele
          testDeleDate
          testDelfdalf
          testDelfdalfDate
          testEnglishPending
          testGmat
          testGmatDate
          testGoethe
          testGoetheDate
          testGre
          testGreDate
          testIelts
          testIeltsDate
          testLogicAndReasoningPending
          testOtherLanguagesPending
          testTagemage
          testTagemageDate
          testTcftef
          testTcftefDate
          testToefl
          testToeflDate
          testToeic
          testToeicDate
          validVisa
          createdAt
          updatedAt
          owner
        }
        todo
        tuitionsFeePaymentDate
        visaDate
        createdAt
        updatedAt
        owner
        program {
          id
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          intakeInformation
          intakes
          languages
          lastUpdate
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
          owner
        }
      }
      applicationId
      lastUpdate
      rating
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteFeedback = /* GraphQL */ `
  subscription OnDeleteFeedback($owner: String) {
    onDeleteFeedback(owner: $owner) {
      id
      application {
        id
        admissionResult
        document
        decisionLetterDate
        intake
        interviewDate
        lastUpdate
        modalApplicationCompletedViewed
        notifications {
          date
          description
          descriptionOptions
          link
          seen
          title
          titleOptions
        }
        programId
        steps {
          date
          id
          isMandatory
          label
          status
          timelineLabel
        }
        studentId
        student {
          id
          address
          birthday
          city
          country
          degrees
          disciplines
          educationCountry
          email
          fatherFirstName
          fatherLastName
          firstLanguage
          firstName
          favoritePrograms
          favoriteSchools
          gender
          gradePointAverage
          guardianFirstName
          guardianLastName
          hasMandatoryDocuments
          highestEducationLevel
          lastName
          lastUpdate
          locale
          maritalStatus
          middleName
          modalProfileCompletedViewed
          phoneNumber
          motherFirstName
          motherMaidenName
          nationality
          parentsAddress
          parentsCity
          parentsCountry
          parentsEmail
          parentsPhoneNumber
          passportNumber
          refusedVisa
          refusedVisaReason
          testCambridgeAdvanced
          testCambridgeAdvancedDate
          testCambridgeFirst
          testCambridgeFirstDate
          testCeliCilsItPlida
          testCeliCilsItPlidaDate
          testDele
          testDeleDate
          testDelfdalf
          testDelfdalfDate
          testEnglishPending
          testGmat
          testGmatDate
          testGoethe
          testGoetheDate
          testGre
          testGreDate
          testIelts
          testIeltsDate
          testLogicAndReasoningPending
          testOtherLanguagesPending
          testTagemage
          testTagemageDate
          testTcftef
          testTcftefDate
          testToefl
          testToeflDate
          testToeic
          testToeicDate
          validVisa
          createdAt
          updatedAt
          owner
        }
        todo
        tuitionsFeePaymentDate
        visaDate
        createdAt
        updatedAt
        owner
        program {
          id
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          intakeInformation
          intakes
          languages
          lastUpdate
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
          owner
        }
      }
      applicationId
      lastUpdate
      rating
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateSchool = /* GraphQL */ `
  subscription OnCreateSchool {
    onCreateSchool {
      id
      city
      country
      coverPhoto
      contactEmail
      contactJobTitle
      contactName
      contactPhone
      contractStatus
      creationYear
      description
      institutionType
      internationalStudents
      lastUpdate
      logo
      name
      totalStudents
      slug
      published
      createdAt
      updatedAt
      owner
      programs {
        items {
          id
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          intakeInformation
          intakes
          languages
          lastUpdate
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
    }
  }
`;
export const onUpdateSchool = /* GraphQL */ `
  subscription OnUpdateSchool {
    onUpdateSchool {
      id
      city
      country
      coverPhoto
      contactEmail
      contactJobTitle
      contactName
      contactPhone
      contractStatus
      creationYear
      description
      institutionType
      internationalStudents
      lastUpdate
      logo
      name
      totalStudents
      slug
      published
      createdAt
      updatedAt
      owner
      programs {
        items {
          id
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          intakeInformation
          intakes
          languages
          lastUpdate
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
    }
  }
`;
export const onDeleteSchool = /* GraphQL */ `
  subscription OnDeleteSchool {
    onDeleteSchool {
      id
      city
      country
      coverPhoto
      contactEmail
      contactJobTitle
      contactName
      contactPhone
      contractStatus
      creationYear
      description
      institutionType
      internationalStudents
      lastUpdate
      logo
      name
      totalStudents
      slug
      published
      createdAt
      updatedAt
      owner
      programs {
        items {
          id
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          intakeInformation
          intakes
          languages
          lastUpdate
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
    }
  }
`;
export const onCreateProgram = /* GraphQL */ `
  subscription OnCreateProgram {
    onCreateProgram {
      id
      applicationFee
      applicationFeeCurrency
      city
      costOfLiving
      costOfLivingCurrency
      country
      degree
      description
      discipline
      duration
      durationUnit
      fee
      feeCurrency
      feeUnit
      feesAndFinancing
      gradePointAverage
      highestEducationLevel
      intakeInformation
      intakes
      languages
      lastUpdate
      minimumAge
      minimumWorkExperience
      minimumWorkExperienceUnit
      name
      otherRequirements
      published
      requestedDocuments {
        name
        isMandatory
        storageKey
        description
        condition
        isSpecific
      }
      schedule
      schoolId
      schoolName
      slug
      submissionDeadline
      testCambridgeAdvanced
      testCambridgeFirst
      testCeliCilsItPlida
      testDele
      testDelfdalf
      testGmat
      testGoethe
      testGre
      testIelts
      testTagemage
      testTcftef
      testToefl
      testToeic
      createdAt
      updatedAt
      owner
      school {
        id
        city
        country
        coverPhoto
        contactEmail
        contactJobTitle
        contactName
        contactPhone
        contractStatus
        creationYear
        description
        institutionType
        internationalStudents
        lastUpdate
        logo
        name
        totalStudents
        slug
        published
        createdAt
        updatedAt
        owner
        programs {
          nextToken
        }
      }
    }
  }
`;
export const onUpdateProgram = /* GraphQL */ `
  subscription OnUpdateProgram {
    onUpdateProgram {
      id
      applicationFee
      applicationFeeCurrency
      city
      costOfLiving
      costOfLivingCurrency
      country
      degree
      description
      discipline
      duration
      durationUnit
      fee
      feeCurrency
      feeUnit
      feesAndFinancing
      gradePointAverage
      highestEducationLevel
      intakeInformation
      intakes
      languages
      lastUpdate
      minimumAge
      minimumWorkExperience
      minimumWorkExperienceUnit
      name
      otherRequirements
      published
      requestedDocuments {
        name
        isMandatory
        storageKey
        description
        condition
        isSpecific
      }
      schedule
      schoolId
      schoolName
      slug
      submissionDeadline
      testCambridgeAdvanced
      testCambridgeFirst
      testCeliCilsItPlida
      testDele
      testDelfdalf
      testGmat
      testGoethe
      testGre
      testIelts
      testTagemage
      testTcftef
      testToefl
      testToeic
      createdAt
      updatedAt
      owner
      school {
        id
        city
        country
        coverPhoto
        contactEmail
        contactJobTitle
        contactName
        contactPhone
        contractStatus
        creationYear
        description
        institutionType
        internationalStudents
        lastUpdate
        logo
        name
        totalStudents
        slug
        published
        createdAt
        updatedAt
        owner
        programs {
          nextToken
        }
      }
    }
  }
`;
export const onDeleteProgram = /* GraphQL */ `
  subscription OnDeleteProgram {
    onDeleteProgram {
      id
      applicationFee
      applicationFeeCurrency
      city
      costOfLiving
      costOfLivingCurrency
      country
      degree
      description
      discipline
      duration
      durationUnit
      fee
      feeCurrency
      feeUnit
      feesAndFinancing
      gradePointAverage
      highestEducationLevel
      intakeInformation
      intakes
      languages
      lastUpdate
      minimumAge
      minimumWorkExperience
      minimumWorkExperienceUnit
      name
      otherRequirements
      published
      requestedDocuments {
        name
        isMandatory
        storageKey
        description
        condition
        isSpecific
      }
      schedule
      schoolId
      schoolName
      slug
      submissionDeadline
      testCambridgeAdvanced
      testCambridgeFirst
      testCeliCilsItPlida
      testDele
      testDelfdalf
      testGmat
      testGoethe
      testGre
      testIelts
      testTagemage
      testTcftef
      testToefl
      testToeic
      createdAt
      updatedAt
      owner
      school {
        id
        city
        country
        coverPhoto
        contactEmail
        contactJobTitle
        contactName
        contactPhone
        contractStatus
        creationYear
        description
        institutionType
        internationalStudents
        lastUpdate
        logo
        name
        totalStudents
        slug
        published
        createdAt
        updatedAt
        owner
        programs {
          nextToken
        }
      }
    }
  }
`;
export const onCreatePost = /* GraphQL */ `
  subscription OnCreatePost {
    onCreatePost {
      id
      category
      content
      lastUpdate
      published
      slug
      title
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdatePost = /* GraphQL */ `
  subscription OnUpdatePost {
    onUpdatePost {
      id
      category
      content
      lastUpdate
      published
      slug
      title
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeletePost = /* GraphQL */ `
  subscription OnDeletePost {
    onDeletePost {
      id
      category
      content
      lastUpdate
      published
      slug
      title
      createdAt
      updatedAt
      owner
    }
  }
`;
