/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateStudent = /* GraphQL */ `
  subscription OnCreateStudent($owner: String) {
    onCreateStudent(owner: $owner) {
      id
      email
      phoneNumber
      address
      city
      country
      firstName
      middleName
      lastName
      birthday
      firstLanguage
      passportNumber
      gender
      maritalStatus
      fatherFirstName
      fatherLastName
      motherFirstName
      motherMaidenName
      guardianLastName
      guardianFirstName
      parentsAddress
      parentsCity
      parentsCountry
      parentsPhoneNumber
      parentsEmail
      disciplines
      degrees
      nationality
      educationCountry
      highestEducationLevel
      gradePointAverage
      schoolsAttended {
        name
        address
        city
        country
        primaryLanguageInstruction
        educationLevel
        degreeAwarded
        degreeAwardedOn
        attendedInstitutionFrom
        attendedInstitutionTo
      }
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      testGoethe
      testDele
      testCeliCilsItPlida
      testToeflDate
      testIeltsDate
      testToeicDate
      testTcftefDate
      testDelfdalfDate
      testGreDate
      testGmatDate
      testTagemageDate
      testCambridgeFirstDate
      testCambridgeAdvancedDate
      testGoetheDate
      testDeleDate
      testCeliCilsItPlidaDate
      testEnglishPending
      testOtherLanguagesPending
      testLogicAndReasoningPending
      validVisa
      refusedVisa
      refusedVisaReason
      workExperiences {
        title
        compagnyName
        address
        workedFrom
        workedTo
      }
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      favoritePrograms
      favoriteSchools
      applications {
        items {
          id
          studentId
          programId
          intake
          document
          interviewDate
          admissionResult
          tuitionsFeePaymentDate
          decisionLetterDate
          visaDate
          todo
          modalApplicationCompletedViewed
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      hasMandatoryDocuments
      modalProfileCompletedViewed
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      locale
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateStudent = /* GraphQL */ `
  subscription OnUpdateStudent($owner: String) {
    onUpdateStudent(owner: $owner) {
      id
      email
      phoneNumber
      address
      city
      country
      firstName
      middleName
      lastName
      birthday
      firstLanguage
      passportNumber
      gender
      maritalStatus
      fatherFirstName
      fatherLastName
      motherFirstName
      motherMaidenName
      guardianLastName
      guardianFirstName
      parentsAddress
      parentsCity
      parentsCountry
      parentsPhoneNumber
      parentsEmail
      disciplines
      degrees
      nationality
      educationCountry
      highestEducationLevel
      gradePointAverage
      schoolsAttended {
        name
        address
        city
        country
        primaryLanguageInstruction
        educationLevel
        degreeAwarded
        degreeAwardedOn
        attendedInstitutionFrom
        attendedInstitutionTo
      }
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      testGoethe
      testDele
      testCeliCilsItPlida
      testToeflDate
      testIeltsDate
      testToeicDate
      testTcftefDate
      testDelfdalfDate
      testGreDate
      testGmatDate
      testTagemageDate
      testCambridgeFirstDate
      testCambridgeAdvancedDate
      testGoetheDate
      testDeleDate
      testCeliCilsItPlidaDate
      testEnglishPending
      testOtherLanguagesPending
      testLogicAndReasoningPending
      validVisa
      refusedVisa
      refusedVisaReason
      workExperiences {
        title
        compagnyName
        address
        workedFrom
        workedTo
      }
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      favoritePrograms
      favoriteSchools
      applications {
        items {
          id
          studentId
          programId
          intake
          document
          interviewDate
          admissionResult
          tuitionsFeePaymentDate
          decisionLetterDate
          visaDate
          todo
          modalApplicationCompletedViewed
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      hasMandatoryDocuments
      modalProfileCompletedViewed
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      locale
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteStudent = /* GraphQL */ `
  subscription OnDeleteStudent($owner: String) {
    onDeleteStudent(owner: $owner) {
      id
      email
      phoneNumber
      address
      city
      country
      firstName
      middleName
      lastName
      birthday
      firstLanguage
      passportNumber
      gender
      maritalStatus
      fatherFirstName
      fatherLastName
      motherFirstName
      motherMaidenName
      guardianLastName
      guardianFirstName
      parentsAddress
      parentsCity
      parentsCountry
      parentsPhoneNumber
      parentsEmail
      disciplines
      degrees
      nationality
      educationCountry
      highestEducationLevel
      gradePointAverage
      schoolsAttended {
        name
        address
        city
        country
        primaryLanguageInstruction
        educationLevel
        degreeAwarded
        degreeAwardedOn
        attendedInstitutionFrom
        attendedInstitutionTo
      }
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      testGoethe
      testDele
      testCeliCilsItPlida
      testToeflDate
      testIeltsDate
      testToeicDate
      testTcftefDate
      testDelfdalfDate
      testGreDate
      testGmatDate
      testTagemageDate
      testCambridgeFirstDate
      testCambridgeAdvancedDate
      testGoetheDate
      testDeleDate
      testCeliCilsItPlidaDate
      testEnglishPending
      testOtherLanguagesPending
      testLogicAndReasoningPending
      validVisa
      refusedVisa
      refusedVisaReason
      workExperiences {
        title
        compagnyName
        address
        workedFrom
        workedTo
      }
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      favoritePrograms
      favoriteSchools
      applications {
        items {
          id
          studentId
          programId
          intake
          document
          interviewDate
          admissionResult
          tuitionsFeePaymentDate
          decisionLetterDate
          visaDate
          todo
          modalApplicationCompletedViewed
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      hasMandatoryDocuments
      modalProfileCompletedViewed
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      locale
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateDocument = /* GraphQL */ `
  subscription OnCreateDocument($owner: String) {
    onCreateDocument(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testGoethe
        testDele
        testCeliCilsItPlida
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testGoetheDate
        testDeleDate
        testCeliCilsItPlidaDate
        testEnglishPending
        testOtherLanguagesPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      name
      storageKey
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateDocument = /* GraphQL */ `
  subscription OnUpdateDocument($owner: String) {
    onUpdateDocument(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testGoethe
        testDele
        testCeliCilsItPlida
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testGoetheDate
        testDeleDate
        testCeliCilsItPlidaDate
        testEnglishPending
        testOtherLanguagesPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      name
      storageKey
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteDocument = /* GraphQL */ `
  subscription OnDeleteDocument($owner: String) {
    onDeleteDocument(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testGoethe
        testDele
        testCeliCilsItPlida
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testGoetheDate
        testDeleDate
        testCeliCilsItPlidaDate
        testEnglishPending
        testOtherLanguagesPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      name
      storageKey
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateApplication = /* GraphQL */ `
  subscription OnCreateApplication($owner: String) {
    onCreateApplication(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testGoethe
        testDele
        testCeliCilsItPlida
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testGoetheDate
        testDeleDate
        testCeliCilsItPlidaDate
        testEnglishPending
        testOtherLanguagesPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      programId
      intake
      document
      steps {
        id
        status
        date
        isMandatory
      }
      interviewDate
      admissionResult
      tuitionsFeePaymentDate
      decisionLetterDate
      visaDate
      todo
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      modalApplicationCompletedViewed
      createdAt
      updatedAt
      program {
        applicationFee
        applicationFeeCurrency
        city
        costOfLiving
        costOfLivingCurrency
        country
        degree
        description
        discipline
        duration
        durationUnit
        fee
        feeCurrency
        feeUnit
        feesAndFinancing
        gradePointAverage
        highestEducationLevel
        id
        intakeInformation
        intakes
        languages
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        name
        otherRequirements
        published
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        schedule
        schoolId
        schoolName
        slug
        submissionDeadline
        testCambridgeAdvanced
        testCambridgeFirst
        testCeliCilsItPlida
        testDele
        testDelfdalf
        testGmat
        testGoethe
        testGre
        testIelts
        testTagemage
        testTcftef
        testToefl
        testToeic
        createdAt
        updatedAt
        school {
          city
          country
          coverPhoto
          contactEmail
          contactJobTitle
          contactName
          contactPhone
          creationYear
          description
          id
          institutionType
          internationalStudents
          logo
          name
          totalStudents
          slug
          published
          contractStatus
          createdAt
          updatedAt
        }
      }
      owner
    }
  }
`;
export const onUpdateApplication = /* GraphQL */ `
  subscription OnUpdateApplication($owner: String) {
    onUpdateApplication(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testGoethe
        testDele
        testCeliCilsItPlida
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testGoetheDate
        testDeleDate
        testCeliCilsItPlidaDate
        testEnglishPending
        testOtherLanguagesPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      programId
      intake
      document
      steps {
        id
        status
        date
        isMandatory
      }
      interviewDate
      admissionResult
      tuitionsFeePaymentDate
      decisionLetterDate
      visaDate
      todo
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      modalApplicationCompletedViewed
      createdAt
      updatedAt
      program {
        applicationFee
        applicationFeeCurrency
        city
        costOfLiving
        costOfLivingCurrency
        country
        degree
        description
        discipline
        duration
        durationUnit
        fee
        feeCurrency
        feeUnit
        feesAndFinancing
        gradePointAverage
        highestEducationLevel
        id
        intakeInformation
        intakes
        languages
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        name
        otherRequirements
        published
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        schedule
        schoolId
        schoolName
        slug
        submissionDeadline
        testCambridgeAdvanced
        testCambridgeFirst
        testCeliCilsItPlida
        testDele
        testDelfdalf
        testGmat
        testGoethe
        testGre
        testIelts
        testTagemage
        testTcftef
        testToefl
        testToeic
        createdAt
        updatedAt
        school {
          city
          country
          coverPhoto
          contactEmail
          contactJobTitle
          contactName
          contactPhone
          creationYear
          description
          id
          institutionType
          internationalStudents
          logo
          name
          totalStudents
          slug
          published
          contractStatus
          createdAt
          updatedAt
        }
      }
      owner
    }
  }
`;
export const onDeleteApplication = /* GraphQL */ `
  subscription OnDeleteApplication($owner: String) {
    onDeleteApplication(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testGoethe
        testDele
        testCeliCilsItPlida
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testGoetheDate
        testDeleDate
        testCeliCilsItPlidaDate
        testEnglishPending
        testOtherLanguagesPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      programId
      intake
      document
      steps {
        id
        status
        date
        isMandatory
      }
      interviewDate
      admissionResult
      tuitionsFeePaymentDate
      decisionLetterDate
      visaDate
      todo
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      modalApplicationCompletedViewed
      createdAt
      updatedAt
      program {
        applicationFee
        applicationFeeCurrency
        city
        costOfLiving
        costOfLivingCurrency
        country
        degree
        description
        discipline
        duration
        durationUnit
        fee
        feeCurrency
        feeUnit
        feesAndFinancing
        gradePointAverage
        highestEducationLevel
        id
        intakeInformation
        intakes
        languages
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        name
        otherRequirements
        published
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        schedule
        schoolId
        schoolName
        slug
        submissionDeadline
        testCambridgeAdvanced
        testCambridgeFirst
        testCeliCilsItPlida
        testDele
        testDelfdalf
        testGmat
        testGoethe
        testGre
        testIelts
        testTagemage
        testTcftef
        testToefl
        testToeic
        createdAt
        updatedAt
        school {
          city
          country
          coverPhoto
          contactEmail
          contactJobTitle
          contactName
          contactPhone
          creationYear
          description
          id
          institutionType
          internationalStudents
          logo
          name
          totalStudents
          slug
          published
          contractStatus
          createdAt
          updatedAt
        }
      }
      owner
    }
  }
`;
export const onCreateSearchAlert = /* GraphQL */ `
  subscription OnCreateSearchAlert($owner: String) {
    onCreateSearchAlert(owner: $owner) {
      id
      query
      type
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testGoethe
        testDele
        testCeliCilsItPlida
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testGoetheDate
        testDeleDate
        testCeliCilsItPlidaDate
        testEnglishPending
        testOtherLanguagesPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateSearchAlert = /* GraphQL */ `
  subscription OnUpdateSearchAlert($owner: String) {
    onUpdateSearchAlert(owner: $owner) {
      id
      query
      type
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testGoethe
        testDele
        testCeliCilsItPlida
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testGoetheDate
        testDeleDate
        testCeliCilsItPlidaDate
        testEnglishPending
        testOtherLanguagesPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteSearchAlert = /* GraphQL */ `
  subscription OnDeleteSearchAlert($owner: String) {
    onDeleteSearchAlert(owner: $owner) {
      id
      query
      type
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testGoethe
        testDele
        testCeliCilsItPlida
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testGoetheDate
        testDeleDate
        testCeliCilsItPlidaDate
        testEnglishPending
        testOtherLanguagesPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateFeedback = /* GraphQL */ `
  subscription OnCreateFeedback($owner: String) {
    onCreateFeedback(owner: $owner) {
      id
      rating
      applicationId
      application {
        id
        studentId
        student {
          id
          email
          phoneNumber
          address
          city
          country
          firstName
          middleName
          lastName
          birthday
          firstLanguage
          passportNumber
          gender
          maritalStatus
          fatherFirstName
          fatherLastName
          motherFirstName
          motherMaidenName
          guardianLastName
          guardianFirstName
          parentsAddress
          parentsCity
          parentsCountry
          parentsPhoneNumber
          parentsEmail
          disciplines
          degrees
          nationality
          educationCountry
          highestEducationLevel
          gradePointAverage
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          testGoethe
          testDele
          testCeliCilsItPlida
          testToeflDate
          testIeltsDate
          testToeicDate
          testTcftefDate
          testDelfdalfDate
          testGreDate
          testGmatDate
          testTagemageDate
          testCambridgeFirstDate
          testCambridgeAdvancedDate
          testGoetheDate
          testDeleDate
          testCeliCilsItPlidaDate
          testEnglishPending
          testOtherLanguagesPending
          testLogicAndReasoningPending
          validVisa
          refusedVisa
          refusedVisaReason
          favoritePrograms
          favoriteSchools
          hasMandatoryDocuments
          modalProfileCompletedViewed
          locale
          createdAt
          updatedAt
          owner
        }
        programId
        intake
        document
        steps {
          id
          status
          date
          isMandatory
        }
        interviewDate
        admissionResult
        tuitionsFeePaymentDate
        decisionLetterDate
        visaDate
        todo
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        modalApplicationCompletedViewed
        createdAt
        updatedAt
        program {
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          id
          intakeInformation
          intakes
          languages
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
        }
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateFeedback = /* GraphQL */ `
  subscription OnUpdateFeedback($owner: String) {
    onUpdateFeedback(owner: $owner) {
      id
      rating
      applicationId
      application {
        id
        studentId
        student {
          id
          email
          phoneNumber
          address
          city
          country
          firstName
          middleName
          lastName
          birthday
          firstLanguage
          passportNumber
          gender
          maritalStatus
          fatherFirstName
          fatherLastName
          motherFirstName
          motherMaidenName
          guardianLastName
          guardianFirstName
          parentsAddress
          parentsCity
          parentsCountry
          parentsPhoneNumber
          parentsEmail
          disciplines
          degrees
          nationality
          educationCountry
          highestEducationLevel
          gradePointAverage
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          testGoethe
          testDele
          testCeliCilsItPlida
          testToeflDate
          testIeltsDate
          testToeicDate
          testTcftefDate
          testDelfdalfDate
          testGreDate
          testGmatDate
          testTagemageDate
          testCambridgeFirstDate
          testCambridgeAdvancedDate
          testGoetheDate
          testDeleDate
          testCeliCilsItPlidaDate
          testEnglishPending
          testOtherLanguagesPending
          testLogicAndReasoningPending
          validVisa
          refusedVisa
          refusedVisaReason
          favoritePrograms
          favoriteSchools
          hasMandatoryDocuments
          modalProfileCompletedViewed
          locale
          createdAt
          updatedAt
          owner
        }
        programId
        intake
        document
        steps {
          id
          status
          date
          isMandatory
        }
        interviewDate
        admissionResult
        tuitionsFeePaymentDate
        decisionLetterDate
        visaDate
        todo
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        modalApplicationCompletedViewed
        createdAt
        updatedAt
        program {
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          id
          intakeInformation
          intakes
          languages
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
        }
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteFeedback = /* GraphQL */ `
  subscription OnDeleteFeedback($owner: String) {
    onDeleteFeedback(owner: $owner) {
      id
      rating
      applicationId
      application {
        id
        studentId
        student {
          id
          email
          phoneNumber
          address
          city
          country
          firstName
          middleName
          lastName
          birthday
          firstLanguage
          passportNumber
          gender
          maritalStatus
          fatherFirstName
          fatherLastName
          motherFirstName
          motherMaidenName
          guardianLastName
          guardianFirstName
          parentsAddress
          parentsCity
          parentsCountry
          parentsPhoneNumber
          parentsEmail
          disciplines
          degrees
          nationality
          educationCountry
          highestEducationLevel
          gradePointAverage
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          testGoethe
          testDele
          testCeliCilsItPlida
          testToeflDate
          testIeltsDate
          testToeicDate
          testTcftefDate
          testDelfdalfDate
          testGreDate
          testGmatDate
          testTagemageDate
          testCambridgeFirstDate
          testCambridgeAdvancedDate
          testGoetheDate
          testDeleDate
          testCeliCilsItPlidaDate
          testEnglishPending
          testOtherLanguagesPending
          testLogicAndReasoningPending
          validVisa
          refusedVisa
          refusedVisaReason
          favoritePrograms
          favoriteSchools
          hasMandatoryDocuments
          modalProfileCompletedViewed
          locale
          createdAt
          updatedAt
          owner
        }
        programId
        intake
        document
        steps {
          id
          status
          date
          isMandatory
        }
        interviewDate
        admissionResult
        tuitionsFeePaymentDate
        decisionLetterDate
        visaDate
        todo
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        modalApplicationCompletedViewed
        createdAt
        updatedAt
        program {
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          id
          intakeInformation
          intakes
          languages
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
        }
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateSchool = /* GraphQL */ `
  subscription OnCreateSchool {
    onCreateSchool {
      city
      country
      coverPhoto
      contactEmail
      contactJobTitle
      contactName
      contactPhone
      creationYear
      description
      id
      institutionType
      internationalStudents
      logo
      name
      totalStudents
      slug
      published
      contractStatus
      createdAt
      updatedAt
      programs {
        items {
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          id
          intakeInformation
          intakes
          languages
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;
export const onUpdateSchool = /* GraphQL */ `
  subscription OnUpdateSchool {
    onUpdateSchool {
      city
      country
      coverPhoto
      contactEmail
      contactJobTitle
      contactName
      contactPhone
      creationYear
      description
      id
      institutionType
      internationalStudents
      logo
      name
      totalStudents
      slug
      published
      contractStatus
      createdAt
      updatedAt
      programs {
        items {
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          id
          intakeInformation
          intakes
          languages
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;
export const onDeleteSchool = /* GraphQL */ `
  subscription OnDeleteSchool {
    onDeleteSchool {
      city
      country
      coverPhoto
      contactEmail
      contactJobTitle
      contactName
      contactPhone
      creationYear
      description
      id
      institutionType
      internationalStudents
      logo
      name
      totalStudents
      slug
      published
      contractStatus
      createdAt
      updatedAt
      programs {
        items {
          applicationFee
          applicationFeeCurrency
          city
          costOfLiving
          costOfLivingCurrency
          country
          degree
          description
          discipline
          duration
          durationUnit
          fee
          feeCurrency
          feeUnit
          feesAndFinancing
          gradePointAverage
          highestEducationLevel
          id
          intakeInformation
          intakes
          languages
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          name
          otherRequirements
          published
          schedule
          schoolId
          schoolName
          slug
          submissionDeadline
          testCambridgeAdvanced
          testCambridgeFirst
          testCeliCilsItPlida
          testDele
          testDelfdalf
          testGmat
          testGoethe
          testGre
          testIelts
          testTagemage
          testTcftef
          testToefl
          testToeic
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;
export const onCreateProgram = /* GraphQL */ `
  subscription OnCreateProgram {
    onCreateProgram {
      applicationFee
      applicationFeeCurrency
      city
      costOfLiving
      costOfLivingCurrency
      country
      degree
      description
      discipline
      duration
      durationUnit
      fee
      feeCurrency
      feeUnit
      feesAndFinancing
      gradePointAverage
      highestEducationLevel
      id
      intakeInformation
      intakes
      languages
      minimumAge
      minimumWorkExperience
      minimumWorkExperienceUnit
      name
      otherRequirements
      published
      requestedDocuments {
        name
        isMandatory
        storageKey
        description
        condition
        isSpecific
      }
      schedule
      schoolId
      schoolName
      slug
      submissionDeadline
      testCambridgeAdvanced
      testCambridgeFirst
      testCeliCilsItPlida
      testDele
      testDelfdalf
      testGmat
      testGoethe
      testGre
      testIelts
      testTagemage
      testTcftef
      testToefl
      testToeic
      createdAt
      updatedAt
      school {
        city
        country
        coverPhoto
        contactEmail
        contactJobTitle
        contactName
        contactPhone
        creationYear
        description
        id
        institutionType
        internationalStudents
        logo
        name
        totalStudents
        slug
        published
        contractStatus
        createdAt
        updatedAt
        programs {
          nextToken
        }
      }
    }
  }
`;
export const onUpdateProgram = /* GraphQL */ `
  subscription OnUpdateProgram {
    onUpdateProgram {
      applicationFee
      applicationFeeCurrency
      city
      costOfLiving
      costOfLivingCurrency
      country
      degree
      description
      discipline
      duration
      durationUnit
      fee
      feeCurrency
      feeUnit
      feesAndFinancing
      gradePointAverage
      highestEducationLevel
      id
      intakeInformation
      intakes
      languages
      minimumAge
      minimumWorkExperience
      minimumWorkExperienceUnit
      name
      otherRequirements
      published
      requestedDocuments {
        name
        isMandatory
        storageKey
        description
        condition
        isSpecific
      }
      schedule
      schoolId
      schoolName
      slug
      submissionDeadline
      testCambridgeAdvanced
      testCambridgeFirst
      testCeliCilsItPlida
      testDele
      testDelfdalf
      testGmat
      testGoethe
      testGre
      testIelts
      testTagemage
      testTcftef
      testToefl
      testToeic
      createdAt
      updatedAt
      school {
        city
        country
        coverPhoto
        contactEmail
        contactJobTitle
        contactName
        contactPhone
        creationYear
        description
        id
        institutionType
        internationalStudents
        logo
        name
        totalStudents
        slug
        published
        contractStatus
        createdAt
        updatedAt
        programs {
          nextToken
        }
      }
    }
  }
`;
export const onDeleteProgram = /* GraphQL */ `
  subscription OnDeleteProgram {
    onDeleteProgram {
      applicationFee
      applicationFeeCurrency
      city
      costOfLiving
      costOfLivingCurrency
      country
      degree
      description
      discipline
      duration
      durationUnit
      fee
      feeCurrency
      feeUnit
      feesAndFinancing
      gradePointAverage
      highestEducationLevel
      id
      intakeInformation
      intakes
      languages
      minimumAge
      minimumWorkExperience
      minimumWorkExperienceUnit
      name
      otherRequirements
      published
      requestedDocuments {
        name
        isMandatory
        storageKey
        description
        condition
        isSpecific
      }
      schedule
      schoolId
      schoolName
      slug
      submissionDeadline
      testCambridgeAdvanced
      testCambridgeFirst
      testCeliCilsItPlida
      testDele
      testDelfdalf
      testGmat
      testGoethe
      testGre
      testIelts
      testTagemage
      testTcftef
      testToefl
      testToeic
      createdAt
      updatedAt
      school {
        city
        country
        coverPhoto
        contactEmail
        contactJobTitle
        contactName
        contactPhone
        creationYear
        description
        id
        institutionType
        internationalStudents
        logo
        name
        totalStudents
        slug
        published
        contractStatus
        createdAt
        updatedAt
        programs {
          nextToken
        }
      }
    }
  }
`;
export const onCreatePost = /* GraphQL */ `
  subscription OnCreatePost {
    onCreatePost {
      category
      content
      id
      published
      slug
      title
      createdAt
      updatedAt
    }
  }
`;
export const onUpdatePost = /* GraphQL */ `
  subscription OnUpdatePost {
    onUpdatePost {
      category
      content
      id
      published
      slug
      title
      createdAt
      updatedAt
    }
  }
`;
export const onDeletePost = /* GraphQL */ `
  subscription OnDeletePost {
    onDeletePost {
      category
      content
      id
      published
      slug
      title
      createdAt
      updatedAt
    }
  }
`;
