// @ts-check
import { initSchema } from '@aws-amplify/datastore';
import { schema } from './schema';

const Country = {
  "AF": "AF",
  "AL": "AL",
  "DZ": "DZ",
  "AD": "AD",
  "AO": "AO",
  "AG": "AG",
  "AR": "AR",
  "AM": "AM",
  "AU": "AU",
  "AT": "AT",
  "AZ": "AZ",
  "BS": "BS",
  "BH": "BH",
  "BD": "BD",
  "BB": "BB",
  "BY": "BY",
  "BE": "BE",
  "BZ": "BZ",
  "BJ": "BJ",
  "BT": "BT",
  "BO": "BO",
  "BA": "BA",
  "BW": "BW",
  "BR": "BR",
  "BG": "BG",
  "BF": "BF",
  "BI": "BI",
  "KH": "KH",
  "CM": "CM",
  "CA": "CA",
  "CV": "CV",
  "CF": "CF",
  "TD": "TD",
  "CL": "CL",
  "CN": "CN",
  "CO": "CO",
  "KM": "KM",
  "CG": "CG",
  "CD": "CD",
  "CR": "CR",
  "CI": "CI",
  "HR": "HR",
  "CU": "CU",
  "CY": "CY",
  "CZ": "CZ",
  "DK": "DK",
  "DJ": "DJ",
  "DM": "DM",
  "DO": "DO",
  "EC": "EC",
  "EG": "EG",
  "SV": "SV",
  "GQ": "GQ",
  "ER": "ER",
  "EE": "EE",
  "ET": "ET",
  "FJ": "FJ",
  "FI": "FI",
  "FR": "FR",
  "GA": "GA",
  "GM": "GM",
  "GE": "GE",
  "DE": "DE",
  "GH": "GH",
  "GR": "GR",
  "GD": "GD",
  "GP": "GP",
  "GT": "GT",
  "GN": "GN",
  "GW": "GW",
  "GY": "GY",
  "HT": "HT",
  "VA": "VA",
  "HN": "HN",
  "HK": "HK",
  "HU": "HU",
  "IS": "IS",
  "IN": "IN",
  "ID": "ID",
  "IR": "IR",
  "IQ": "IQ",
  "IE": "IE",
  "IL": "IL",
  "IT": "IT",
  "JM": "JM",
  "JP": "JP",
  "JO": "JO",
  "KZ": "KZ",
  "KE": "KE",
  "KI": "KI",
  "KP": "KP",
  "KR": "KR",
  "KW": "KW",
  "KG": "KG",
  "LA": "LA",
  "LV": "LV",
  "LB": "LB",
  "LS": "LS",
  "LR": "LR",
  "LY": "LY",
  "LI": "LI",
  "LT": "LT",
  "LU": "LU",
  "MO": "MO",
  "MK": "MK",
  "MG": "MG",
  "MW": "MW",
  "MY": "MY",
  "MV": "MV",
  "ML": "ML",
  "MT": "MT",
  "MH": "MH",
  "MR": "MR",
  "MU": "MU",
  "MX": "MX",
  "FM": "FM",
  "MD": "MD",
  "MC": "MC",
  "MN": "MN",
  "ME": "ME",
  "MA": "MA",
  "MZ": "MZ",
  "MM": "MM",
  "NA": "NA",
  "NR": "NR",
  "NP": "NP",
  "NL": "NL",
  "NZ": "NZ",
  "NI": "NI",
  "NE": "NE",
  "NG": "NG",
  "NO": "NO",
  "OM": "OM",
  "PK": "PK",
  "PW": "PW",
  "PS": "PS",
  "PA": "PA",
  "PG": "PG",
  "PY": "PY",
  "PE": "PE",
  "PH": "PH",
  "PL": "PL",
  "PT": "PT",
  "QA": "QA",
  "RO": "RO",
  "RU": "RU",
  "RW": "RW",
  "KN": "KN",
  "LC": "LC",
  "VC": "VC",
  "WS": "WS",
  "SM": "SM",
  "ST": "ST",
  "SA": "SA",
  "SN": "SN",
  "RS": "RS",
  "SC": "SC",
  "SL": "SL",
  "SG": "SG",
  "SK": "SK",
  "SI": "SI",
  "SB": "SB",
  "SO": "SO",
  "ZA": "ZA",
  "SS": "SS",
  "ES": "ES",
  "LK": "LK",
  "SD": "SD",
  "SR": "SR",
  "SE": "SE",
  "CH": "CH",
  "SY": "SY",
  "TW": "TW",
  "TJ": "TJ",
  "TZ": "TZ",
  "TH": "TH",
  "TL": "TL",
  "TG": "TG",
  "TO": "TO",
  "TT": "TT",
  "TN": "TN",
  "TR": "TR",
  "TM": "TM",
  "TV": "TV",
  "UG": "UG",
  "UA": "UA",
  "AE": "AE",
  "GB": "GB",
  "US": "US",
  "UY": "UY",
  "UZ": "UZ",
  "VU": "VU",
  "VE": "VE",
  "VN": "VN",
  "YE": "YE",
  "ZM": "ZM",
  "ZW": "ZW"
};

const ContractStatus = {
  "PRIORITY": "PRIORITY",
  "CONTACTED": "CONTACTED",
  "IN_NEGOCIATION": "IN_NEGOCIATION",
  "SIGNED": "SIGNED"
};

const Currency = {
  "CHF": "CHF",
  "CNY": "CNY",
  "EUR": "EUR",
  "GBP": "GBP"
};

const Degree = {
  "BACHELOR": "BACHELOR",
  "MASTER": "MASTER",
  "DOCTORATE": "DOCTORATE"
};

const Discipline = {
  "BUSINESS_MANAGEMENT_AND_ECONOMICS": "BUSINESS_MANAGEMENT_AND_ECONOMICS",
  "ENGINEERING_AND_TECHNOLOGY": "ENGINEERING_AND_TECHNOLOGY",
  "SCIENCES": "SCIENCES",
  "CULINARY_ARTS": "CULINARY_ARTS",
  "LAW_POLITICS_SOCIAL_COMMUNITY_SERVICE_AND_TEACHING": "LAW_POLITICS_SOCIAL_COMMUNITY_SERVICE_AND_TEACHING",
  "ARTS": "ARTS",
  "HEALTH_SCIENCES_MEDICINE_NURSING_PARAMEDIC_AND_KINESIOLOGY": "HEALTH_SCIENCES_MEDICINE_NURSING_PARAMEDIC_AND_KINESIOLOGY",
  "ENGLISH_FOR_ACADEMIC_STUDIES": "ENGLISH_FOR_ACADEMIC_STUDIES"
};

const DurationUnit = {
  "DAY": "DAY",
  "MONTH": "MONTH",
  "YEAR": "YEAR",
  "WEEK": "WEEK"
};

const FeeUnit = {
  "YEAR": "YEAR",
  "TOTAL": "TOTAL"
};

const InstitutionType = {
  "PRIVATE": "PRIVATE",
  "PUBLIC": "PUBLIC"
};

const Language = {
  "AF": "AF",
  "SQ": "SQ",
  "AR": "AR",
  "HY": "HY",
  "EU": "EU",
  "BN": "BN",
  "BG": "BG",
  "CA": "CA",
  "KM": "KM",
  "ZH": "ZH",
  "HR": "HR",
  "CS": "CS",
  "DA": "DA",
  "NL": "NL",
  "EN": "EN",
  "ET": "ET",
  "FJ": "FJ",
  "FI": "FI",
  "FR": "FR",
  "KA": "KA",
  "DE": "DE",
  "EL": "EL",
  "GU": "GU",
  "HE": "HE",
  "HI": "HI",
  "HU": "HU",
  "IS": "IS",
  "ID": "ID",
  "GA": "GA",
  "IT": "IT",
  "JA": "JA",
  "JW": "JW",
  "KO": "KO",
  "LA": "LA",
  "LV": "LV",
  "LT": "LT",
  "MK": "MK",
  "MS": "MS",
  "ML": "ML",
  "MT": "MT",
  "MI": "MI",
  "MR": "MR",
  "MN": "MN",
  "NE": "NE",
  "NO": "NO",
  "FA": "FA",
  "PL": "PL",
  "PT": "PT",
  "PA": "PA",
  "QU": "QU",
  "RO": "RO",
  "RU": "RU",
  "SM": "SM",
  "SR": "SR",
  "SK": "SK",
  "SL": "SL",
  "ES": "ES",
  "SW": "SW",
  "SV": "SV",
  "TA": "TA",
  "TT": "TT",
  "TE": "TE",
  "TH": "TH",
  "BO": "BO",
  "TO": "TO",
  "TR": "TR",
  "UK": "UK",
  "UR": "UR",
  "UZ": "UZ",
  "VI": "VI",
  "CY": "CY",
  "XH": "XH"
};

const Schedule = {
  "FULL_TIME": "FULL_TIME",
  "PART_TIME": "PART_TIME"
};

const { School, Program, Student, Document, Application, SearchAlert, Feedback, RequestedDocument, ApplicationStepsTemplate, ApplicationStep, SchoolAttended, WorkExperience, Notification } = initSchema(schema);

export {
  School,
  Program,
  Student,
  Document,
  Application,
  SearchAlert,
  Feedback,
  Country,
  ContractStatus,
  Currency,
  Degree,
  Discipline,
  DurationUnit,
  FeeUnit,
  InstitutionType,
  Language,
  Schedule,
  RequestedDocument,
  ApplicationStepsTemplate,
  ApplicationStep,
  SchoolAttended,
  WorkExperience,
  Notification
};