/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const subscribeToStudentUpdate = /* GraphQL */ `
  subscription SubscribeToStudentUpdate($id: ID!) {
    subscribeToStudentUpdate(id: $id) {
      id
      email
      phoneNumber
      address
      city
      country
      firstName
      middleName
      lastName
      birthday
      firstLanguage
      passportNumber
      gender
      maritalStatus
      fatherFirstName
      fatherLastName
      motherFirstName
      motherMaidenName
      guardianLastName
      guardianFirstName
      parentsAddress
      parentsCity
      parentsCountry
      parentsPhoneNumber
      parentsEmail
      disciplines
      degrees
      nationality
      educationCountry
      highestEducationLevel
      gradePointAverage
      schoolsAttended {
        name
        address
        city
        country
        primaryLanguageInstruction
        educationLevel
        degreeAwarded
        degreeAwardedOn
        attendedInstitutionFrom
        attendedInstitutionTo
      }
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      testToeflDate
      testIeltsDate
      testToeicDate
      testTcftefDate
      testDelfdalfDate
      testGreDate
      testGmatDate
      testTagemageDate
      testCambridgeFirstDate
      testCambridgeAdvancedDate
      testEnglishPending
      testFrenchPending
      testLogicAndReasoningPending
      validVisa
      refusedVisa
      refusedVisaReason
      workExperiences {
        title
        compagnyName
        address
        workedFrom
        workedTo
      }
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      favoritePrograms
      favoriteSchools
      applications {
        items {
          id
          studentId
          programId
          intake
          document
          interviewDate
          admissionResult
          tuitionsFeePaymentDate
          decisionLetterDate
          visaDate
          todo
          modalApplicationCompletedViewed
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      hasMandatoryDocuments
      modalProfileCompletedViewed
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      locale
      createdAt
      updatedAt
      owner
    }
  }
`;
export const subscribeToApplicationUpdate = /* GraphQL */ `
  subscription SubscribeToApplicationUpdate($id: ID!) {
    subscribeToApplicationUpdate(id: $id) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      programId
      intake
      document
      steps {
        id
        status
        date
        isMandatory
      }
      interviewDate
      admissionResult
      tuitionsFeePaymentDate
      decisionLetterDate
      visaDate
      todo
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      modalApplicationCompletedViewed
      createdAt
      updatedAt
      program {
        id
        schoolId
        schoolName
        slug
        name
        city
        country
        discipline
        degree
        duration
        durationUnit
        schedule
        languages
        fee
        feeUnit
        feeCurrency
        intakes
        intakeInformation
        submissionDeadline
        costOfLiving
        costOfLivingCurrency
        description
        gradePointAverage
        highestEducationLevel
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        otherRequirements
        applicationFee
        applicationFeeCurrency
        feesAndFinancing
        published
        createdAt
        updatedAt
        school {
          id
          slug
          name
          city
          country
          totalStudents
          internationalStudents
          institutionType
          creationYear
          description
          logo
          coverPhoto
          contactJobTitle
          contactName
          contactPhone
          contactEmail
          published
          contractStatus
          createdAt
          updatedAt
        }
      }
      owner
    }
  }
`;
export const onCreateStudent = /* GraphQL */ `
  subscription OnCreateStudent($owner: String) {
    onCreateStudent(owner: $owner) {
      id
      email
      phoneNumber
      address
      city
      country
      firstName
      middleName
      lastName
      birthday
      firstLanguage
      passportNumber
      gender
      maritalStatus
      fatherFirstName
      fatherLastName
      motherFirstName
      motherMaidenName
      guardianLastName
      guardianFirstName
      parentsAddress
      parentsCity
      parentsCountry
      parentsPhoneNumber
      parentsEmail
      disciplines
      degrees
      nationality
      educationCountry
      highestEducationLevel
      gradePointAverage
      schoolsAttended {
        name
        address
        city
        country
        primaryLanguageInstruction
        educationLevel
        degreeAwarded
        degreeAwardedOn
        attendedInstitutionFrom
        attendedInstitutionTo
      }
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      testToeflDate
      testIeltsDate
      testToeicDate
      testTcftefDate
      testDelfdalfDate
      testGreDate
      testGmatDate
      testTagemageDate
      testCambridgeFirstDate
      testCambridgeAdvancedDate
      testEnglishPending
      testFrenchPending
      testLogicAndReasoningPending
      validVisa
      refusedVisa
      refusedVisaReason
      workExperiences {
        title
        compagnyName
        address
        workedFrom
        workedTo
      }
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      favoritePrograms
      favoriteSchools
      applications {
        items {
          id
          studentId
          programId
          intake
          document
          interviewDate
          admissionResult
          tuitionsFeePaymentDate
          decisionLetterDate
          visaDate
          todo
          modalApplicationCompletedViewed
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      hasMandatoryDocuments
      modalProfileCompletedViewed
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      locale
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateStudent = /* GraphQL */ `
  subscription OnUpdateStudent($owner: String) {
    onUpdateStudent(owner: $owner) {
      id
      email
      phoneNumber
      address
      city
      country
      firstName
      middleName
      lastName
      birthday
      firstLanguage
      passportNumber
      gender
      maritalStatus
      fatherFirstName
      fatherLastName
      motherFirstName
      motherMaidenName
      guardianLastName
      guardianFirstName
      parentsAddress
      parentsCity
      parentsCountry
      parentsPhoneNumber
      parentsEmail
      disciplines
      degrees
      nationality
      educationCountry
      highestEducationLevel
      gradePointAverage
      schoolsAttended {
        name
        address
        city
        country
        primaryLanguageInstruction
        educationLevel
        degreeAwarded
        degreeAwardedOn
        attendedInstitutionFrom
        attendedInstitutionTo
      }
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      testToeflDate
      testIeltsDate
      testToeicDate
      testTcftefDate
      testDelfdalfDate
      testGreDate
      testGmatDate
      testTagemageDate
      testCambridgeFirstDate
      testCambridgeAdvancedDate
      testEnglishPending
      testFrenchPending
      testLogicAndReasoningPending
      validVisa
      refusedVisa
      refusedVisaReason
      workExperiences {
        title
        compagnyName
        address
        workedFrom
        workedTo
      }
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      favoritePrograms
      favoriteSchools
      applications {
        items {
          id
          studentId
          programId
          intake
          document
          interviewDate
          admissionResult
          tuitionsFeePaymentDate
          decisionLetterDate
          visaDate
          todo
          modalApplicationCompletedViewed
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      hasMandatoryDocuments
      modalProfileCompletedViewed
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      locale
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteStudent = /* GraphQL */ `
  subscription OnDeleteStudent($owner: String) {
    onDeleteStudent(owner: $owner) {
      id
      email
      phoneNumber
      address
      city
      country
      firstName
      middleName
      lastName
      birthday
      firstLanguage
      passportNumber
      gender
      maritalStatus
      fatherFirstName
      fatherLastName
      motherFirstName
      motherMaidenName
      guardianLastName
      guardianFirstName
      parentsAddress
      parentsCity
      parentsCountry
      parentsPhoneNumber
      parentsEmail
      disciplines
      degrees
      nationality
      educationCountry
      highestEducationLevel
      gradePointAverage
      schoolsAttended {
        name
        address
        city
        country
        primaryLanguageInstruction
        educationLevel
        degreeAwarded
        degreeAwardedOn
        attendedInstitutionFrom
        attendedInstitutionTo
      }
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      testToeflDate
      testIeltsDate
      testToeicDate
      testTcftefDate
      testDelfdalfDate
      testGreDate
      testGmatDate
      testTagemageDate
      testCambridgeFirstDate
      testCambridgeAdvancedDate
      testEnglishPending
      testFrenchPending
      testLogicAndReasoningPending
      validVisa
      refusedVisa
      refusedVisaReason
      workExperiences {
        title
        compagnyName
        address
        workedFrom
        workedTo
      }
      documents {
        items {
          id
          studentId
          name
          storageKey
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      favoritePrograms
      favoriteSchools
      applications {
        items {
          id
          studentId
          programId
          intake
          document
          interviewDate
          admissionResult
          tuitionsFeePaymentDate
          decisionLetterDate
          visaDate
          todo
          modalApplicationCompletedViewed
          createdAt
          updatedAt
          owner
        }
        nextToken
      }
      hasMandatoryDocuments
      modalProfileCompletedViewed
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      locale
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateDocument = /* GraphQL */ `
  subscription OnCreateDocument($owner: String) {
    onCreateDocument(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      name
      storageKey
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateDocument = /* GraphQL */ `
  subscription OnUpdateDocument($owner: String) {
    onUpdateDocument(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      name
      storageKey
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteDocument = /* GraphQL */ `
  subscription OnDeleteDocument($owner: String) {
    onDeleteDocument(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      name
      storageKey
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateApplication = /* GraphQL */ `
  subscription OnCreateApplication($owner: String) {
    onCreateApplication(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      programId
      intake
      document
      steps {
        id
        status
        date
        isMandatory
      }
      interviewDate
      admissionResult
      tuitionsFeePaymentDate
      decisionLetterDate
      visaDate
      todo
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      modalApplicationCompletedViewed
      createdAt
      updatedAt
      program {
        id
        schoolId
        schoolName
        slug
        name
        city
        country
        discipline
        degree
        duration
        durationUnit
        schedule
        languages
        fee
        feeUnit
        feeCurrency
        intakes
        intakeInformation
        submissionDeadline
        costOfLiving
        costOfLivingCurrency
        description
        gradePointAverage
        highestEducationLevel
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        otherRequirements
        applicationFee
        applicationFeeCurrency
        feesAndFinancing
        published
        createdAt
        updatedAt
        school {
          id
          slug
          name
          city
          country
          totalStudents
          internationalStudents
          institutionType
          creationYear
          description
          logo
          coverPhoto
          contactJobTitle
          contactName
          contactPhone
          contactEmail
          published
          contractStatus
          createdAt
          updatedAt
        }
      }
      owner
    }
  }
`;
export const onUpdateApplication = /* GraphQL */ `
  subscription OnUpdateApplication($owner: String) {
    onUpdateApplication(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      programId
      intake
      document
      steps {
        id
        status
        date
        isMandatory
      }
      interviewDate
      admissionResult
      tuitionsFeePaymentDate
      decisionLetterDate
      visaDate
      todo
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      modalApplicationCompletedViewed
      createdAt
      updatedAt
      program {
        id
        schoolId
        schoolName
        slug
        name
        city
        country
        discipline
        degree
        duration
        durationUnit
        schedule
        languages
        fee
        feeUnit
        feeCurrency
        intakes
        intakeInformation
        submissionDeadline
        costOfLiving
        costOfLivingCurrency
        description
        gradePointAverage
        highestEducationLevel
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        otherRequirements
        applicationFee
        applicationFeeCurrency
        feesAndFinancing
        published
        createdAt
        updatedAt
        school {
          id
          slug
          name
          city
          country
          totalStudents
          internationalStudents
          institutionType
          creationYear
          description
          logo
          coverPhoto
          contactJobTitle
          contactName
          contactPhone
          contactEmail
          published
          contractStatus
          createdAt
          updatedAt
        }
      }
      owner
    }
  }
`;
export const onDeleteApplication = /* GraphQL */ `
  subscription OnDeleteApplication($owner: String) {
    onDeleteApplication(owner: $owner) {
      id
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      programId
      intake
      document
      steps {
        id
        status
        date
        isMandatory
      }
      interviewDate
      admissionResult
      tuitionsFeePaymentDate
      decisionLetterDate
      visaDate
      todo
      notifications {
        title
        titleOptions
        description
        descriptionOptions
        date
        seen
        link
      }
      modalApplicationCompletedViewed
      createdAt
      updatedAt
      program {
        id
        schoolId
        schoolName
        slug
        name
        city
        country
        discipline
        degree
        duration
        durationUnit
        schedule
        languages
        fee
        feeUnit
        feeCurrency
        intakes
        intakeInformation
        submissionDeadline
        costOfLiving
        costOfLivingCurrency
        description
        gradePointAverage
        highestEducationLevel
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        requestedDocuments {
          name
          isMandatory
          storageKey
          description
          condition
          isSpecific
        }
        minimumAge
        minimumWorkExperience
        minimumWorkExperienceUnit
        otherRequirements
        applicationFee
        applicationFeeCurrency
        feesAndFinancing
        published
        createdAt
        updatedAt
        school {
          id
          slug
          name
          city
          country
          totalStudents
          internationalStudents
          institutionType
          creationYear
          description
          logo
          coverPhoto
          contactJobTitle
          contactName
          contactPhone
          contactEmail
          published
          contractStatus
          createdAt
          updatedAt
        }
      }
      owner
    }
  }
`;
export const onCreateSearchAlert = /* GraphQL */ `
  subscription OnCreateSearchAlert($owner: String) {
    onCreateSearchAlert(owner: $owner) {
      id
      query
      type
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateSearchAlert = /* GraphQL */ `
  subscription OnUpdateSearchAlert($owner: String) {
    onUpdateSearchAlert(owner: $owner) {
      id
      query
      type
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteSearchAlert = /* GraphQL */ `
  subscription OnDeleteSearchAlert($owner: String) {
    onDeleteSearchAlert(owner: $owner) {
      id
      query
      type
      studentId
      student {
        id
        email
        phoneNumber
        address
        city
        country
        firstName
        middleName
        lastName
        birthday
        firstLanguage
        passportNumber
        gender
        maritalStatus
        fatherFirstName
        fatherLastName
        motherFirstName
        motherMaidenName
        guardianLastName
        guardianFirstName
        parentsAddress
        parentsCity
        parentsCountry
        parentsPhoneNumber
        parentsEmail
        disciplines
        degrees
        nationality
        educationCountry
        highestEducationLevel
        gradePointAverage
        schoolsAttended {
          name
          address
          city
          country
          primaryLanguageInstruction
          educationLevel
          degreeAwarded
          degreeAwardedOn
          attendedInstitutionFrom
          attendedInstitutionTo
        }
        testToefl
        testIelts
        testToeic
        testTcftef
        testDelfdalf
        testGre
        testGmat
        testTagemage
        testCambridgeFirst
        testCambridgeAdvanced
        testToeflDate
        testIeltsDate
        testToeicDate
        testTcftefDate
        testDelfdalfDate
        testGreDate
        testGmatDate
        testTagemageDate
        testCambridgeFirstDate
        testCambridgeAdvancedDate
        testEnglishPending
        testFrenchPending
        testLogicAndReasoningPending
        validVisa
        refusedVisa
        refusedVisaReason
        workExperiences {
          title
          compagnyName
          address
          workedFrom
          workedTo
        }
        documents {
          nextToken
        }
        favoritePrograms
        favoriteSchools
        applications {
          nextToken
        }
        hasMandatoryDocuments
        modalProfileCompletedViewed
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        locale
        createdAt
        updatedAt
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateFeedback = /* GraphQL */ `
  subscription OnCreateFeedback($owner: String) {
    onCreateFeedback(owner: $owner) {
      id
      rating
      applicationId
      application {
        id
        studentId
        student {
          id
          email
          phoneNumber
          address
          city
          country
          firstName
          middleName
          lastName
          birthday
          firstLanguage
          passportNumber
          gender
          maritalStatus
          fatherFirstName
          fatherLastName
          motherFirstName
          motherMaidenName
          guardianLastName
          guardianFirstName
          parentsAddress
          parentsCity
          parentsCountry
          parentsPhoneNumber
          parentsEmail
          disciplines
          degrees
          nationality
          educationCountry
          highestEducationLevel
          gradePointAverage
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          testToeflDate
          testIeltsDate
          testToeicDate
          testTcftefDate
          testDelfdalfDate
          testGreDate
          testGmatDate
          testTagemageDate
          testCambridgeFirstDate
          testCambridgeAdvancedDate
          testEnglishPending
          testFrenchPending
          testLogicAndReasoningPending
          validVisa
          refusedVisa
          refusedVisaReason
          favoritePrograms
          favoriteSchools
          hasMandatoryDocuments
          modalProfileCompletedViewed
          locale
          createdAt
          updatedAt
          owner
        }
        programId
        intake
        document
        steps {
          id
          status
          date
          isMandatory
        }
        interviewDate
        admissionResult
        tuitionsFeePaymentDate
        decisionLetterDate
        visaDate
        todo
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        modalApplicationCompletedViewed
        createdAt
        updatedAt
        program {
          id
          schoolId
          schoolName
          slug
          name
          city
          country
          discipline
          degree
          duration
          durationUnit
          schedule
          languages
          fee
          feeUnit
          feeCurrency
          intakes
          intakeInformation
          submissionDeadline
          costOfLiving
          costOfLivingCurrency
          description
          gradePointAverage
          highestEducationLevel
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          otherRequirements
          applicationFee
          applicationFeeCurrency
          feesAndFinancing
          published
          createdAt
          updatedAt
        }
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateFeedback = /* GraphQL */ `
  subscription OnUpdateFeedback($owner: String) {
    onUpdateFeedback(owner: $owner) {
      id
      rating
      applicationId
      application {
        id
        studentId
        student {
          id
          email
          phoneNumber
          address
          city
          country
          firstName
          middleName
          lastName
          birthday
          firstLanguage
          passportNumber
          gender
          maritalStatus
          fatherFirstName
          fatherLastName
          motherFirstName
          motherMaidenName
          guardianLastName
          guardianFirstName
          parentsAddress
          parentsCity
          parentsCountry
          parentsPhoneNumber
          parentsEmail
          disciplines
          degrees
          nationality
          educationCountry
          highestEducationLevel
          gradePointAverage
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          testToeflDate
          testIeltsDate
          testToeicDate
          testTcftefDate
          testDelfdalfDate
          testGreDate
          testGmatDate
          testTagemageDate
          testCambridgeFirstDate
          testCambridgeAdvancedDate
          testEnglishPending
          testFrenchPending
          testLogicAndReasoningPending
          validVisa
          refusedVisa
          refusedVisaReason
          favoritePrograms
          favoriteSchools
          hasMandatoryDocuments
          modalProfileCompletedViewed
          locale
          createdAt
          updatedAt
          owner
        }
        programId
        intake
        document
        steps {
          id
          status
          date
          isMandatory
        }
        interviewDate
        admissionResult
        tuitionsFeePaymentDate
        decisionLetterDate
        visaDate
        todo
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        modalApplicationCompletedViewed
        createdAt
        updatedAt
        program {
          id
          schoolId
          schoolName
          slug
          name
          city
          country
          discipline
          degree
          duration
          durationUnit
          schedule
          languages
          fee
          feeUnit
          feeCurrency
          intakes
          intakeInformation
          submissionDeadline
          costOfLiving
          costOfLivingCurrency
          description
          gradePointAverage
          highestEducationLevel
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          otherRequirements
          applicationFee
          applicationFeeCurrency
          feesAndFinancing
          published
          createdAt
          updatedAt
        }
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteFeedback = /* GraphQL */ `
  subscription OnDeleteFeedback($owner: String) {
    onDeleteFeedback(owner: $owner) {
      id
      rating
      applicationId
      application {
        id
        studentId
        student {
          id
          email
          phoneNumber
          address
          city
          country
          firstName
          middleName
          lastName
          birthday
          firstLanguage
          passportNumber
          gender
          maritalStatus
          fatherFirstName
          fatherLastName
          motherFirstName
          motherMaidenName
          guardianLastName
          guardianFirstName
          parentsAddress
          parentsCity
          parentsCountry
          parentsPhoneNumber
          parentsEmail
          disciplines
          degrees
          nationality
          educationCountry
          highestEducationLevel
          gradePointAverage
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          testToeflDate
          testIeltsDate
          testToeicDate
          testTcftefDate
          testDelfdalfDate
          testGreDate
          testGmatDate
          testTagemageDate
          testCambridgeFirstDate
          testCambridgeAdvancedDate
          testEnglishPending
          testFrenchPending
          testLogicAndReasoningPending
          validVisa
          refusedVisa
          refusedVisaReason
          favoritePrograms
          favoriteSchools
          hasMandatoryDocuments
          modalProfileCompletedViewed
          locale
          createdAt
          updatedAt
          owner
        }
        programId
        intake
        document
        steps {
          id
          status
          date
          isMandatory
        }
        interviewDate
        admissionResult
        tuitionsFeePaymentDate
        decisionLetterDate
        visaDate
        todo
        notifications {
          title
          titleOptions
          description
          descriptionOptions
          date
          seen
          link
        }
        modalApplicationCompletedViewed
        createdAt
        updatedAt
        program {
          id
          schoolId
          schoolName
          slug
          name
          city
          country
          discipline
          degree
          duration
          durationUnit
          schedule
          languages
          fee
          feeUnit
          feeCurrency
          intakes
          intakeInformation
          submissionDeadline
          costOfLiving
          costOfLivingCurrency
          description
          gradePointAverage
          highestEducationLevel
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          otherRequirements
          applicationFee
          applicationFeeCurrency
          feesAndFinancing
          published
          createdAt
          updatedAt
        }
        owner
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateSchool = /* GraphQL */ `
  subscription OnCreateSchool {
    onCreateSchool {
      id
      slug
      name
      city
      country
      totalStudents
      internationalStudents
      institutionType
      creationYear
      description
      logo
      coverPhoto
      contactJobTitle
      contactName
      contactPhone
      contactEmail
      published
      stepsTemplates {
        targets
        steps {
          id
          status
          date
          isMandatory
        }
      }
      contractStatus
      createdAt
      updatedAt
      programs {
        items {
          id
          schoolId
          schoolName
          slug
          name
          city
          country
          discipline
          degree
          duration
          durationUnit
          schedule
          languages
          fee
          feeUnit
          feeCurrency
          intakes
          intakeInformation
          submissionDeadline
          costOfLiving
          costOfLivingCurrency
          description
          gradePointAverage
          highestEducationLevel
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          otherRequirements
          applicationFee
          applicationFeeCurrency
          feesAndFinancing
          published
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;
export const onUpdateSchool = /* GraphQL */ `
  subscription OnUpdateSchool {
    onUpdateSchool {
      id
      slug
      name
      city
      country
      totalStudents
      internationalStudents
      institutionType
      creationYear
      description
      logo
      coverPhoto
      contactJobTitle
      contactName
      contactPhone
      contactEmail
      published
      stepsTemplates {
        targets
        steps {
          id
          status
          date
          isMandatory
        }
      }
      contractStatus
      createdAt
      updatedAt
      programs {
        items {
          id
          schoolId
          schoolName
          slug
          name
          city
          country
          discipline
          degree
          duration
          durationUnit
          schedule
          languages
          fee
          feeUnit
          feeCurrency
          intakes
          intakeInformation
          submissionDeadline
          costOfLiving
          costOfLivingCurrency
          description
          gradePointAverage
          highestEducationLevel
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          otherRequirements
          applicationFee
          applicationFeeCurrency
          feesAndFinancing
          published
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;
export const onDeleteSchool = /* GraphQL */ `
  subscription OnDeleteSchool {
    onDeleteSchool {
      id
      slug
      name
      city
      country
      totalStudents
      internationalStudents
      institutionType
      creationYear
      description
      logo
      coverPhoto
      contactJobTitle
      contactName
      contactPhone
      contactEmail
      published
      stepsTemplates {
        targets
        steps {
          id
          status
          date
          isMandatory
        }
      }
      contractStatus
      createdAt
      updatedAt
      programs {
        items {
          id
          schoolId
          schoolName
          slug
          name
          city
          country
          discipline
          degree
          duration
          durationUnit
          schedule
          languages
          fee
          feeUnit
          feeCurrency
          intakes
          intakeInformation
          submissionDeadline
          costOfLiving
          costOfLivingCurrency
          description
          gradePointAverage
          highestEducationLevel
          testToefl
          testIelts
          testToeic
          testTcftef
          testDelfdalf
          testGre
          testGmat
          testTagemage
          testCambridgeFirst
          testCambridgeAdvanced
          minimumAge
          minimumWorkExperience
          minimumWorkExperienceUnit
          otherRequirements
          applicationFee
          applicationFeeCurrency
          feesAndFinancing
          published
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;
export const onCreateProgram = /* GraphQL */ `
  subscription OnCreateProgram {
    onCreateProgram {
      id
      schoolId
      schoolName
      slug
      name
      city
      country
      discipline
      degree
      duration
      durationUnit
      schedule
      languages
      fee
      feeUnit
      feeCurrency
      intakes
      intakeInformation
      submissionDeadline
      costOfLiving
      costOfLivingCurrency
      description
      gradePointAverage
      highestEducationLevel
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      requestedDocuments {
        name
        isMandatory
        storageKey
        description
        condition
        isSpecific
      }
      minimumAge
      minimumWorkExperience
      minimumWorkExperienceUnit
      otherRequirements
      applicationFee
      applicationFeeCurrency
      feesAndFinancing
      published
      createdAt
      updatedAt
      school {
        id
        slug
        name
        city
        country
        totalStudents
        internationalStudents
        institutionType
        creationYear
        description
        logo
        coverPhoto
        contactJobTitle
        contactName
        contactPhone
        contactEmail
        published
        stepsTemplates {
          targets
        }
        contractStatus
        createdAt
        updatedAt
        programs {
          nextToken
        }
      }
    }
  }
`;
export const onUpdateProgram = /* GraphQL */ `
  subscription OnUpdateProgram {
    onUpdateProgram {
      id
      schoolId
      schoolName
      slug
      name
      city
      country
      discipline
      degree
      duration
      durationUnit
      schedule
      languages
      fee
      feeUnit
      feeCurrency
      intakes
      intakeInformation
      submissionDeadline
      costOfLiving
      costOfLivingCurrency
      description
      gradePointAverage
      highestEducationLevel
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      requestedDocuments {
        name
        isMandatory
        storageKey
        description
        condition
        isSpecific
      }
      minimumAge
      minimumWorkExperience
      minimumWorkExperienceUnit
      otherRequirements
      applicationFee
      applicationFeeCurrency
      feesAndFinancing
      published
      createdAt
      updatedAt
      school {
        id
        slug
        name
        city
        country
        totalStudents
        internationalStudents
        institutionType
        creationYear
        description
        logo
        coverPhoto
        contactJobTitle
        contactName
        contactPhone
        contactEmail
        published
        stepsTemplates {
          targets
        }
        contractStatus
        createdAt
        updatedAt
        programs {
          nextToken
        }
      }
    }
  }
`;
export const onDeleteProgram = /* GraphQL */ `
  subscription OnDeleteProgram {
    onDeleteProgram {
      id
      schoolId
      schoolName
      slug
      name
      city
      country
      discipline
      degree
      duration
      durationUnit
      schedule
      languages
      fee
      feeUnit
      feeCurrency
      intakes
      intakeInformation
      submissionDeadline
      costOfLiving
      costOfLivingCurrency
      description
      gradePointAverage
      highestEducationLevel
      testToefl
      testIelts
      testToeic
      testTcftef
      testDelfdalf
      testGre
      testGmat
      testTagemage
      testCambridgeFirst
      testCambridgeAdvanced
      requestedDocuments {
        name
        isMandatory
        storageKey
        description
        condition
        isSpecific
      }
      minimumAge
      minimumWorkExperience
      minimumWorkExperienceUnit
      otherRequirements
      applicationFee
      applicationFeeCurrency
      feesAndFinancing
      published
      createdAt
      updatedAt
      school {
        id
        slug
        name
        city
        country
        totalStudents
        internationalStudents
        institutionType
        creationYear
        description
        logo
        coverPhoto
        contactJobTitle
        contactName
        contactPhone
        contactEmail
        published
        stepsTemplates {
          targets
        }
        contractStatus
        createdAt
        updatedAt
        programs {
          nextToken
        }
      }
    }
  }
`;
export const onCreatePost = /* GraphQL */ `
  subscription OnCreatePost {
    onCreatePost {
      category
      content
      id
      published
      slug
      title
      createdAt
      updatedAt
    }
  }
`;
export const onUpdatePost = /* GraphQL */ `
  subscription OnUpdatePost {
    onUpdatePost {
      category
      content
      id
      published
      slug
      title
      createdAt
      updatedAt
    }
  }
`;
export const onDeletePost = /* GraphQL */ `
  subscription OnDeletePost {
    onDeletePost {
      category
      content
      id
      published
      slug
      title
      createdAt
      updatedAt
    }
  }
`;
