on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]
name: Main
jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Get master branch
              run: git fetch origin master
            - name: Install dependencies
              run: npm install
            - name: Install Jest globally
              run: sudo npm install -g jest
            - name: Run tests
              run: npm run test
            - name: SonarCloud scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      design-system:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: yarn
            - name: Deploy to Chromatic
              uses: chromaui/action@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}