name: main
on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Get master branch
              run: git fetch origin master
            - name: Install dependencies
              run: yarn install
            - name: Install Jest globally
              run: sudo yarn global add jest
            - name: Run unit tests
              run: yarn test
            - name: SonarCloud scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎
              uses: actions/checkout@v2

            - name: Run e2e tests
              uses: cypress-io/github-action@v1
              with:
                  start: yarn start:students
                  command: yarn cy:run:students
