on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]
name: Code quality
jobs:
    sonarcloud:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Get master branch
              run: git fetch origin master
            - name: Install dependencies
              run: npm install
            - name: Install Jest globally
              run: sudo npm install -g jest
            - name: Run tests
              run: npm run test
            - name: SonarCloud scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
