name: unit-tests
on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Get master branch
              run: git fetch origin master
            - name: Install dependencies
              run: yarn install
            - name: Install Jest globally
              run: sudo yarn global add jest
            - name: Run tests
              run: yarn test
            - name: SonarCloud scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      e2e-tests:
        if: github.event.deployment_status.state == 'success'
        runs-on: ubuntu-latest
        steps:
          - name: Checkout 🛎
            uses: actions/checkout@v1
          - name: Run Cypress 🌲
            uses: cypress-io/github-action@v2
            env:
              CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}

